### ISSUE TITLE
Multiple schemas/connections in a MEAN app

### ISSUE THREAD

**Issue by LaFrish** [ga-wdi-exercises/project4#170]
https://github.com/LaFrish/beachhouse

I am having issues trying to connect multiple schemas/connections to my mean app (no angular yet). 

``` js
connection.js

var mongoose = require("mongoose");

var MixologistSchema = new mongoose.Schema(
  {
    drink_name: String,
    ingredients: [String],
    instructions: String
  }
);

var BoomboxSchema = new mongoose.Schema(
  {
    playlist_name: String,
    playlist_url: String
  }
);

var PhotoboothSchema = new mongoose.Schema(
  {
    photo_name: String,
    photo_type: String
  }
);


//from documentation

var db = mongoose.createConnection("mongodb://localhost/"),
  Mixologist = db.model("Mixologist");
  Boombox = db.model("Boombox");
  Photobooth = db.model("Photobooth");

// Important: the actual interaction with the data happens with the Model that you obtain through //mongoose.model or db.model. That's the object that you can instantiate or that you can call .find(), //.findOne(), etc upon. Don't confuse schemas and actual models!

mongoose.model("Mixologist", MixologistSchema);
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGOLAB_URL);
}else{
  mongoose.connect("mongodb://localhost/mixologist");
}
mongoose.model("Boombox", BoomboxSchema);
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGOLAB_URL);
}else{
  mongoose.connect("mongodb://localhost/boombox");
}

mongoose.model("Photobooth", PhotoboothSchema);
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGOLAB_URL);
}else{
  mongoose.connect("mongodb://localhost/photobooth");
}


module.exports = mongoose;
mixologist
boombox
photobooth
```

```
seed.js
var mongoose = require("./connection");
var seedData = require("./seeds");

var Mixologist = mongoose.model("Mixologist");
var Boombox = mongoose.model("Boombox");
var Photobooth = mongoose.model("Photobooth");

Mixologist.remove({}).then(function(){
  Mixologist.collection.insert(seedData).then(function(){
    process.exit();
  });
});

Boombox.remove({}).then(function(){
  Boombox.collection.insert(seedData).then(function(){
    process.exit();
  });
});

Photobooth.remove({}).then(function(){
  Photobooth.collection.insert(seedData).then(function(){
    process.exit();
  });
});
```

```
top of index.js

var express = require("express");
var parser  = require("body-parser");
var hbs     = require("express-handlebars");
var session = require("express-session");
var request = require("request");
var qstring = require("qs");
var cmongo = require("connect-mongo");
var mongoose= require("./db/connection");
var twitter = require("./lib/twitter_auth");

var app     = express();
var SMongo = cmongo(session);


var Mixologist = mongoose.model("Mixologist");
var Boombox = mongoose.model("Boombox");
var Photobooth = mongoose.model("Photobooth");

if(process.env.NODE_ENV !== "production"){
  var env   = require("./env");
  process.env.session_secret = env.session_secret;
  process.env.t_callback_url = env.t_callback_url;
  process.env.t_consumer_key = env.t_consumer_key;
  process.env.t_consumer_secret = env.t_consumer_secret;
}

app.use(session({
  secret: process.env.session_secret,
  resave: false,
  saveUninitialized: false,
  store: new SMongo({
    mongooseConnection: mongoose.connection
  })
}));
```

**Comment by RobertAKARobin** [comment]
You're connecting to your database 3 times. You only need to connect once, regardless of the number of models you have.

**Comment by LaFrish** [comment]
Any suggestions on how to do that???

**Comment by RobertAKARobin** [comment]
Remove 2 of the 3 blocks where you have those `mongoose.connect` bits.

**Comment by LaFrish** [comment]
So all that will fix the problems?

**Comment by RobertAKARobin** [comment]
One way to find out!

**Comment by LaFrish** [comment]
lol i already did it smartass.

**Comment by LaFrish** [comment]
and no it didn't help.

**Comment by RobertAKARobin** [comment]
Are you getting a different error?

**Comment by RobertAKARobin** [comment]
Also, make sure you `npm install --save express` to put express in your `package.json`.

**Comment by LaFrish** [comment]
```
/Users/LaFrish/wdi/projects/project5/beachhouse/node_modules/mongoose/lib/index.js:349
      throw new mongoose.Error.MissingSchemaError(name);
      ^
MissingSchemaError: Schema hasn't been registered for model "Boombox".
Use mongoose.model(name, schema)
    at Mongoose.model (/Users/LaFrish/wdi/projects/project5/beachhouse/node_modules/mongoose/lib/index.js:349:13)
    at Object.<anonymous> (/Users/LaFrish/wdi/projects/project5/beachhouse/index.js:16:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by LaFrish** [comment]
i removed 

```
var Boombox = mongoose.model("Boombox");
var Photobooth = mongoose.model("Photobooth");
```

from index.js  and it is working BUT does that mean I can't have a database for these 2 completely separate items?

**Comment by RobertAKARobin** [comment]
The `mongoose.connect` tries to connect to a whole new database every time it's read. You only have one database; therefore, you only need `mongoose.connect` once.

Also, the `db.model` thing you have in there is the same thing as the `mongoose.model` thing you also have in there 3 times.

**Comment by RobertAKARobin** [comment]
I made a PR request with some recommended changes:

https://github.com/LaFrish/beachhouse/pull/1

**Comment by LaFrish** [comment]
ok  thx

**Comment by RobertAKARobin** [comment]
Why have databases for separate items? That's what tables are for!

**Comment by LaFrish** [comment]
lol nevermind that then. 

Did you see the comment about the seedData on the issue request?

**Comment by RobertAKARobin** [comment]
No... where?

**Comment by RobertAKARobin** [comment]
But there's an error in your seeds.json. Run it through www.jsonlint.com

**Comment by LaFrish** [comment]
I must have deleted it when I added the snippets. How do I manage the seedData for the different "tables". Do I have three separate seed files named diff or do I have it all in one?

**Comment by RobertAKARobin** [comment]
Either way, really, but I'd say do it in separate JSON files.

**Comment by LaFrish** [comment]
k. thanks for your help Captain.

**Comment by RobertAKARobin** [comment]
👍
