### ISSUE TITLE
syntax errors leading to "site not found"

### ISSUE THREAD

**Issue by Dibbledl01** [ga-wdi-exercises/project4#182]
Good Morning!

Link to repo: https://github.com/Dibbledl01/AppOfHonor

I'm back to my app for Maids of Honor! It's a MEAN stack "to-do" list app for Maids of Honor. It initially was working, but it's my goal to essentially add "lists within lists." Meaning, I was able to render the initial list categories, broken down by how many months out from the wedding the MOH is. But, I then want a list to live within that category, detailing what she needs to do

For example, a user can click on "Day of Wedding." That will then render a list with such tasks as "keep bride calm" or "bring cash for make up artist."

I tried adding some code to begin that list within a list process, but I believe that's what's throwing me errors.

Here are the errors I'm being thrown:
In my CL when I run node db/connection.js:
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

in my CL when I run nodemon index.js:
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/brittanydibble/AppOfHonor/index.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
[nodemon] app crashed - waiting for file changes before starting...

And then when I try to visit localhost:3001/ I get "this site can't be reached"

Thanks so much!

**Comment by mattscilipoti** [comment]
Your application can not start, due to a syntax error, therefore “this site can’t be reached.”  Your experiments indicate that there is square bracket where you wouldn’t expect one to be in "db/connection.js” ("SyntaxError: Unexpected token [“).

**Comment by amaseda** [comment]
Was writing something out but now: what Matt said! Take a look at your `connection.js` file 😉
