### ISSUE TITLE
Deployment of app to heroku was successful, but then I get this error:

### ISSUE THREAD

**Issue by mvaden** [ga-wdi-exercises/project4#228]
I was successful in deploying my app to heroku. However, the following error in Chrome rendered below:
![screen shot 2016-06-02 at 11 57 35 am](https://cloud.githubusercontent.com/assets/17731291/15751939/f97d5c44-28b9-11e6-8e7e-8473c8c76819.pngDep

This is the deployment history + logs:

```
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ bundle install
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types-data 3.2016.0221
Using arel 6.0.3
Using debug_inspector 0.0.2
Using byebug 9.0.4
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using thor 0.19.1
Using concurrent-ruby 1.0.2
Using multi_json 1.12.1
Using pg 0.18.4
Using bundler 1.11.2
Using sass 3.4.22
Using tilt 2.0.4
Using spring 1.7.1
Using rdoc 4.2.2
Using tzinfo 1.2.2
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using mime-types 3.0
Using binding_of_caller 0.7.2
Using coffee-script 2.4.1
Using uglifier 3.0.0
Using sprockets 3.6.0
Using sdoc 0.4.1
Using activesupport 4.2.6
Using loofah 2.0.3
Using mail 2.6.4
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.6
Using jbuilder 2.4.1
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using activejob 4.2.6
Using activerecord 4.2.6
Using actionview 4.2.6
Using actionpack 4.2.6
Using actionmailer 4.2.6
Using railties 4.2.6
Using sprockets-rails 3.0.4
Using coffee-rails 4.1.1
Using jquery-rails 4.1.1
Using rails 4.2.6
Using sass-rails 5.0.4
Using web-console 2.3.0
Using turbolinks 2.5.3
Bundle complete! 12 Gemfile dependencies, 55 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git add .
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git commit -m "Deploying wherearetheynow"
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku create wherearetheynow
Creating ⬢ wherearetheynow... !!!
 ▸    You've reached the limit of 5 apps for unverified accounts.
 ▸    Delete some apps or add a credit card to verify your account.
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku create wherearetheynow
Creating ⬢ wherearetheynow... done
https://wherearetheynow.herokuapp.com/ | https://git.heroku.com/wherearetheynow.git
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git push heroku master
Counting objects: 289, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (270/270), done.
Writing objects: 100% (289/289), 10.53 MiB | 1.73 MiB/s, done.
Total 289 (delta 109), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.2.4
remote: -----> Installing dependencies using bundler 1.11.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Fetching gem metadata from https://rubygems.org/...........
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Installing i18n 0.7.0
remote:        Installing rake 11.1.2
remote:        Installing json 1.8.3 with native extensions
remote:        Installing minitest 5.9.0
remote:        Installing thread_safe 0.3.5
remote:        Installing builder 3.2.2
remote:        Installing erubis 2.7.0
remote:        Installing mini_portile2 2.0.0
remote:        Installing rack 1.6.4
remote:        Installing mime-types-data 3.2016.0221
remote:        Installing arel 6.0.3
remote:        Installing execjs 2.7.0
remote:        Installing coffee-script-source 1.10.0
remote:        Installing thor 0.19.1
remote:        Installing concurrent-ruby 1.0.2
remote:        Using bundler 1.11.2
remote:        Installing multi_json 1.12.1
remote:        Installing pg 0.18.4 with native extensions
remote:        Installing tilt 2.0.4
remote:        Installing sass 3.4.22
remote:        Installing tzinfo 1.2.2
remote:        Installing nokogiri 1.6.7.2 with native extensions
remote:        Installing rack-test 0.6.3
remote:        Installing rdoc 4.2.2
remote:        Installing mime-types 3.0
remote:        Installing uglifier 3.0.0
remote:        Installing coffee-script 2.4.1
remote:        Installing sprockets 3.6.0
remote:        Installing activesupport 4.2.6
remote:        Installing sdoc 0.4.1
remote:        Installing mail 2.6.4
remote:        Installing rails-deprecated_sanitizer 1.0.3
remote:        Installing globalid 0.3.6
remote:        Installing activemodel 4.2.6
remote:        Installing jbuilder 2.4.1
remote:        Installing activejob 4.2.6
remote:        Installing activerecord 4.2.6
remote:        Installing loofah 2.0.3
remote:        Installing rails-dom-testing 1.0.7
remote:        Installing rails-html-sanitizer 1.0.3
remote:        Installing actionview 4.2.6
remote:        Installing actionpack 4.2.6
remote:        Installing sprockets-rails 3.0.4
remote:        Installing actionmailer 4.2.6
remote:        Installing railties 4.2.6
remote:        Installing coffee-rails 4.1.1
remote:        Installing jquery-rails 4.1.1
remote:        Installing rails 4.2.6
remote:        Installing sass-rails 5.0.4
remote:        Installing turbolinks 2.5.3
remote:        Bundle complete! 12 Gemfile dependencies, 50 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Post-install message from rdoc:
remote:        Depending on your version of ruby, you may need to install ruby rdoc/ri data:
remote:        <= 1.8.6 : unsupported
remote:        = 1.8.7 : gem install rdoc-data; rdoc-data --install
remote:        = 1.9.1 : gem install rdoc-data; rdoc-data --install
remote:        >= 1.9.2 : nothing to do! Yay!
remote:        Bundle completed (29.77s)
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        I, [2016-06-02T15:37:05.623503 #1029]  INFO -- : Writing /tmp/build_84341e6767fbfad9f916a8ebcf6146d4/public/assets/application-47feac84829615907e7d9e9e4f934dda30e6ccdaf38f2cd263a63797d486050d.js
remote:        I, [2016-06-02T15:37:05.624438 #1029]  INFO -- : Writing /tmp/build_84341e6767fbfad9f916a8ebcf6146d4/public/assets/application-47feac84829615907e7d9e9e4f934dda30e6ccdaf38f2cd263a63797d486050d.js.gz
remote:        I, [2016-06-02T15:37:05.640563 #1029]  INFO -- : Writing /tmp/build_84341e6767fbfad9f916a8ebcf6146d4/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.cs
remote:        I, [2016-06-02T15:37:05.640746 #1029]  INFO -- : Writing /tmp/build_84341e6767fbfad9f916a8ebcf6146d4/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css.gz
remote:        Asset precompilation completed (4.53s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
remote: 
remote: ###### WARNING:
remote:        Include 'rails_12factor' gem to enable all platform features
remote:        See https://devcenter.heroku.com/articles/rails-integration-gems for more information.
remote: 
remote: ###### WARNING:
remote:        You have not declared a Ruby version in your Gemfile.
remote:        To set your Ruby version add this line to your Gemfile
remote:        ruby '2.2.4'
remote:        # See https://devcenter.heroku.com/articles/ruby-versions for more information.
remote: 
remote: ###### WARNING:
remote:        No Procfile detected, using the default web server.
remote:        We recommend explicitly declaring how to boot your server process via a Procfile.
remote:        https://devcenter.heroku.com/articles/ruby-default-web-server
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> console, rake, web, worker
remote: 
remote: -----> Compressing...
remote:        Done: 40.4M
remote: -----> Launching...
remote:        Released v5
remote:        https://wherearetheynow.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/wherearetheynow.git
 * [new branch]      master -> master
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku run rake db:migrate
Running rake db:migrate on ⬢ wherearetheynow... up, run.6099
== 20160601055833 CreateClassmates: migrating =================================
-- create_table(:classmates)
   -> 0.0710s
== 20160601055833 CreateClassmates: migrated (0.0736s) ========================

== 20160602025603 CreateComments: migrating ===================================
-- create_table(:comments)
   -> 0.0083s
== 20160602025603 CreateComments: migrated (0.0114s) ==========================

== 20160602145114 AddClassmateIdToComments: migrating =========================
-- add_column(:comments, :classmate_id, :integer)
   -> 0.0056s
== 20160602145114 AddClassmateIdToComments: migrated (0.0060s) ================

Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku run rake db:seed
Running rake db:seed on ⬢ wherearetheynow... up, run.8486
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku open
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku logs -t
2016-06-02T15:35:57.424899+00:00 heroku[api]: Release v2 created by mvaden08@gmail.com
2016-06-02T15:35:57.424825+00:00 heroku[api]: Enable Logplex by mvaden08@gmail.com
2016-06-02T15:37:15.470457+00:00 heroku[api]: Set LANG, RACK_ENV, RAILS_ENV, RAILS_SERVE_STATIC_FILES, SECRET_KEY_BASE config vars by mvaden08@gmail.com
2016-06-02T15:37:15.470506+00:00 heroku[api]: Release v3 created by mvaden08@gmail.com
2016-06-02T15:37:17.437821+00:00 heroku[slug-compiler]: Slug compilation started
2016-06-02T15:37:17.437832+00:00 heroku[slug-compiler]: Slug compilation finished
2016-06-02T15:37:16.232963+00:00 heroku[api]: Release v4 created by mvaden08@gmail.com
2016-06-02T15:37:16.232890+00:00 heroku[api]: Attach DATABASE (@ref:postgresql-graceful-91219) by mvaden08@gmail.com
2016-06-02T15:37:16.771297+00:00 heroku[api]: Release v5 created by mvaden08@gmail.com
2016-06-02T15:37:16.771187+00:00 heroku[api]: Deploy 817abe8 by mvaden08@gmail.com
2016-06-02T15:37:16.770412+00:00 heroku[api]: Scale to web=1 by mvaden08@gmail.com
2016-06-02T15:37:19.932285+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 25916 -e production`
2016-06-02T15:37:25.449251+00:00 app[web.1]: [2016-06-02 15:37:25] INFO  ruby 2.2.4 (2015-12-16) [x86_64-linux]
2016-06-02T15:37:25.449630+00:00 app[web.1]: [2016-06-02 15:37:25] INFO  WEBrick::HTTPServer#start: pid=3 port=25916
2016-06-02T15:37:25.449238+00:00 app[web.1]: [2016-06-02 15:37:25] INFO  WEBrick 1.3.1
2016-06-02T15:37:25.842559+00:00 heroku[web.1]: State changed from starting to up
2016-06-02T15:37:52.004531+00:00 heroku[api]: Starting process with command `bundle exec rake db:migrate` by mvaden08@gmail.com
2016-06-02T15:37:55.658783+00:00 heroku[run.6099]: Starting process with command `bundle exec rake db:migrate`
2016-06-02T15:37:55.626466+00:00 heroku[run.6099]: Awaiting client
2016-06-02T15:37:55.900215+00:00 heroku[run.6099]: State changed from starting to up
2016-06-02T15:38:01.842556+00:00 heroku[run.6099]: Process exited with status 0
2016-06-02T15:38:01.860108+00:00 heroku[run.6099]: State changed from up to complete
2016-06-02T15:40:27.382508+00:00 heroku[api]: Starting process with command `bundle exec rake db:seed` by mvaden08@gmail.com
2016-06-02T15:40:31.150228+00:00 heroku[run.8486]: Awaiting client
2016-06-02T15:40:31.191068+00:00 heroku[run.8486]: Starting process with command `bundle exec rake db:seed`
2016-06-02T15:40:31.215626+00:00 heroku[run.8486]: State changed from starting to up
2016-06-02T15:40:37.929234+00:00 heroku[run.8486]: Process exited with status 0
2016-06-02T15:40:37.942387+00:00 heroku[run.8486]: State changed from up to complete
2016-06-02T15:41:49.886732+00:00 heroku[router]: at=info method=GET path="/" host=wherearetheynow.herokuapp.com request_id=7b62cf51-c316-4889-96d3-6a377d581fd7 fwd="50.200.196.50" dyno=web.1 connect=0ms service=58ms status=404 bytes=1829
2016-06-02T15:41:50.084978+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=wherearetheynow.herokuapp.com request_id=e267a5a4-3380-429c-b3eb-92bbab36115b fwd="50.200.196.50" dyno=web.1 connect=0ms service=4ms status=200 bytes=228
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git add .
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    modified:   config/environments/production.rb

Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git commit -m "config.assets.compile is now set to true."
[master 785f765] config.assets.compile is now set to true.
 1 file changed, 1 insertion(+), 1 deletion(-)
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git push heroku master
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 488 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Using set buildpack heroku/ruby
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.2.4
remote: -----> Installing dependencies using bundler 1.11.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Using rake 11.1.2
remote:        Using i18n 0.7.0
remote:        Using json 1.8.3
remote:        Using minitest 5.9.0
remote:        Using thread_safe 0.3.5
remote:        Using builder 3.2.2
remote:        Using erubis 2.7.0
remote:        Using mini_portile2 2.0.0
remote:        Using rack 1.6.4
remote:        Using mime-types-data 3.2016.0221
remote:        Using arel 6.0.3
remote:        Using coffee-script-source 1.10.0
remote:        Using execjs 2.7.0
remote:        Using thor 0.19.1
remote:        Using concurrent-ruby 1.0.2
remote:        Using multi_json 1.12.1
remote:        Using pg 0.18.4
remote:        Using bundler 1.11.2
remote:        Using sass 3.4.22
remote:        Using tilt 2.0.4
remote:        Using rdoc 4.2.2
remote:        Using tzinfo 1.2.2
remote:        Using nokogiri 1.6.7.2
remote:        Using mime-types 3.0
remote:        Using rack-test 0.6.3
remote:        Using coffee-script 2.4.1
remote:        Using uglifier 3.0.0
remote:        Using sprockets 3.6.0
remote:        Using activesupport 4.2.6
remote:        Using loofah 2.0.3
remote:        Using mail 2.6.4
remote:        Using sdoc 0.4.1
remote:        Using rails-html-sanitizer 1.0.3
remote:        Using rails-deprecated_sanitizer 1.0.3
remote:        Using globalid 0.3.6
remote:        Using activemodel 4.2.6
remote:        Using jbuilder 2.4.1
remote:        Using activejob 4.2.6
remote:        Using activerecord 4.2.6
remote:        Using rails-dom-testing 1.0.7
remote:        Using actionview 4.2.6
remote:        Using actionpack 4.2.6
remote:        Using actionmailer 4.2.6
remote:        Using railties 4.2.6
remote:        Using sprockets-rails 3.0.4
remote:        Using coffee-rails 4.1.1
remote:        Using jquery-rails 4.1.1
remote:        Using rails 4.2.6
remote:        Using sass-rails 5.0.4
remote:        Using turbolinks 2.5.3
remote:        Bundle complete! 12 Gemfile dependencies, 50 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (0.35s)
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        Asset precompilation completed (1.44s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
remote: 
remote: ###### WARNING:
remote:        Include 'rails_12factor' gem to enable all platform features
remote:        See https://devcenter.heroku.com/articles/rails-integration-gems for more information.
remote: 
remote: ###### WARNING:
remote:        You have not declared a Ruby version in your Gemfile.
remote:        To set your Ruby version add this line to your Gemfile
remote:        ruby '2.2.4'
remote:        # See https://devcenter.heroku.com/articles/ruby-versions for more information.
remote: 
remote: ###### WARNING:
remote:        No Procfile detected, using the default web server.
remote:        We recommend explicitly declaring how to boot your server process via a Procfile.
remote:        https://devcenter.heroku.com/articles/ruby-default-web-server
remote: 
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> console, rake, web, worker
remote: 
remote: -----> Compressing...
remote:        Done: 40.4M
remote: -----> Launching...
remote:        Released v6
remote:        https://wherearetheynow.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/wherearetheynow.git
   817abe8..785f765  master -> master
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ git push origin master
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 488 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/mvaden/wherearetheynow.git
To git@github.com:mvaden/Project_4.git
   817abe8..785f765  master -> master
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku open
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku rake db:migrate
WARNING: `heroku rake` has been deprecated. Please use `heroku run rake` instead.
Running `rake db:migrate` attached to terminal... up, run.6167
Matthews-MacBook-Air-2:wherearetheynow MrVaden$ heroku run rake db:setup
Running rake db:setup on ⬢ wherearetheynow... up, run.7728
FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:87:in `connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:93:in `create'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:274:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `invoke_prerequisites'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:207:in `invoke_prerequisites'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
/app/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"d6doa30djctit7", "username"=>"krfkvqzavrrcsa", "password"=>"WA--una9Jktds1AHWzzXb9hGZ0", "port"=>5432, "host"=>"ec2-174-129-242-241.compute-1.amazonaws.com"}
-- enable_extension("plpgsql")
   -> 0.0704s
-- create_table("classmates", {:force=>:cascade})
   -> 0.0407s
-- create_table("comments", {:force=>:cascade})
   -> 0.0245s
-- initialize_schema_migrations_table()
   -> 0.0392s
Matthews-MacBook-Air-2:wherearetheynow MrVaden$
```

**Comment by tylercrosse** [comment]
`gem "rails_12factor", group: :production`
