### ISSUE TITLE
Migration Issue

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/project4#274]
Not sure how to fix error... I checked for all of the instances of "team_names" that I can think of...

Stack Trace Follows:

```
michaelparks@Michaels-MacBook-Pro-2:~/Desktop/File-Cabinet/_Projects/GA/project4/waylow (waylow-streamline) $rake db:drop db:create db:migrate db:seed
Dropped database 'waylow_development'
Dropped database 'waylow_test'
Created database 'waylow_development'
Created database 'waylow_test'
== 20160806201127 CreateCompetitions: migrating ===============================
-- create_table(:competitions)
   -> 0.0094s
== 20160806201127 CreateCompetitions: migrated (0.0095s) ======================

== 20160806201407 CreateWeighIns: migrating ===================================
-- create_table(:weigh_ins)
   -> 0.0070s
== 20160806201407 CreateWeighIns: migrated (0.0071s) ==========================

== 20160806201436 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0053s
== 20160806201436 CreateUsers: migrated (0.0054s) =============================

== 20160806203321 AddCompetitionRefToWeighIn: migrating =======================
-- add_reference(:weigh_ins, :competition, {:foreign_key=>true})
   -> 0.0124s
== 20160806203321 AddCompetitionRefToWeighIn: migrated (0.0126s) ==============

== 20160806203358 AddUserRefToWeighIn: migrating ==============================
-- add_reference(:weigh_ins, :user, {:foreign_key=>true})
   -> 0.0089s
== 20160806203358 AddUserRefToWeighIn: migrated (0.0091s) =====================

== 20160810143233 CreateParticipants: migrating ===============================
-- create_table(:participants)
   -> 0.0051s
== 20160810143233 CreateParticipants: migrated (0.0052s) ======================

== 20160810144025 CreateStages: migrating =====================================
-- create_table(:stages)
   -> 0.0072s
== 20160810144025 CreateStages: migrated (0.0073s) ============================

== 20160810144111 CreateTeams: migrating ======================================
-- create_table(:teams)
   -> 0.0064s
== 20160810144111 CreateTeams: migrated (0.0065s) =============================

rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'team_names' for Competition.
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.0/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.0/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.0/lib/active_model/attribute_assignment.rb:39:in `each'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.0/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.0/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/core.rb:319:in `initialize'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/inheritance.rb:65:in `new'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/inheritance.rb:65:in `new'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/persistence.rb:33:in `create'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/persistence.rb:31:in `block in create'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/persistence.rb:31:in `collect'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/persistence.rb:31:in `create'
/Users/michaelparks/Desktop/File-Cabinet/_Projects/GA/project4/waylow/db/seeds.rb:6:in `<top (required)>'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:549:in `load_seed'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:268:in `load_seed'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/michaelparks/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
michaelparks@Michaels-MacBook-Pro-2:~/Desktop/File-Cabinet/_Projects/GA/project4/waylow (waylow-streamline) $

```

**Comment by ayespi** [comment]
Does me being on a branch other than the master make a difference???

**Comment by nolds9** [comment]
@ayespi double check and make sure your migration to create  your `Competitions`  table, includes a field called `team_names`...instead of trying all the commands at once, try each command individually so you can tell if it errors on the migration or on seeding.

**Comment by ayespi** [comment]
Well blow me down! The Stack Trace did say that the migration was complete... It is the seed... Thanks!

**Comment by amaseda** [comment]
How's this going @ayespi? Any progress / more questions?

**Comment by ayespi** [comment]
Slight...

**Comment by jshawl** [comment]
anything we can help with?

**Comment by ayespi** [comment]
Heroku Deployment Failed!!! I submitted a issue...

**Comment by jshawl** [comment]
What is the output in the terminal?

**Comment by ayespi** [comment]
Thanks for responding I was able to resolve issue... Now, I am deployed but the app is not showing up... I think I need to do the Heroku rake commands and I should be fine... We'll see...
