### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project4#359]
I tried deploying my app on heroku but I am getting an error when I got to the link they provided.  I did not see any issues in the CLI when I added the git url.  I checked the heroku logs and I see that there is an issue, but I am not sure how to read the error.

![screen shot 2016-11-30 at 10 43 49 am](https://cloud.githubusercontent.com/assets/20979785/20759206/38b369e4-b6ea-11e6-89d2-6e83c409ceb8.png)

![screen shot 2016-11-30 at 10 43 37 am](https://cloud.githubusercontent.com/assets/20979785/20759210/3c1df23e-b6ea-11e6-9f1e-34b5deb6c0c3.png)

**Comment by nolds9** [comment]
What is your technology stack? What did you try?

**Comment by jshawl** [comment]
this appears to be the same issue - https://github.com/ga-wdi-exercises/project4/issues/352

**Comment by griffind2009** [comment]
I'm using the MEAN stack

**Comment by griffind2009** [comment]
would i use this? 
"scripts": {
  "start": "node index.js",
  "test": "mocha",
  "postinstall": "bower install && grunt build"
}

**Comment by jshawl** [comment]
try it out! only need the start part though

**Comment by griffind2009** [comment]
I added the script start and it still wasn't working. so i added "app.listen(process.env.PORT || 4200)" and did heroku open and it worked.  However, my data isn't showing and I can't use the drop down search box.
![screen shot 2016-11-30 at 11 09 06 am](https://cloud.githubusercontent.com/assets/20979785/20760257/802ab216-b6ed-11e6-8747-2c331d7468d7.png)

![screen shot 2016-11-30 at 11 08 57 am](https://cloud.githubusercontent.com/assets/20979785/20760261/85040788-b6ed-11e6-83db-51c4a4eae751.png)

**Comment by jshawl** [comment]
did you run your seed data?

**Comment by griffind2009** [comment]
I just tried running it "node db/seed.js" and refreshed the browser but nothing happened

**Comment by nolds9** [comment]
you need to run that command in the context of heroku

**Comment by jshawl** [comment]
`heroku run node db/seed.js`

**Comment by griffind2009** [comment]
ok, i just tried that and got this error. i am not sure why it is trying to connect to localhost:27017
![screen shot 2016-11-30 at 11 16 45 am](https://cloud.githubusercontent.com/assets/20979785/20760629/8bc319c8-b6ee-11e6-8e24-dd584783682e.png)

**Comment by nolds9** [comment]
can you search your codebase for `localhost:27017`? my guess is it's where you are connecting to your mongodb, and since you are using heroku, you need to specify a different host + port. I would look into using `mongolab` to host your database https://devcenter.heroku.com/articles/mongolab#connecting-to-existing-mlab-deployments-from-heroku

**Comment by griffind2009** [comment]
I don't see localhost:27017 anywhere in my code

**Comment by jshawl** [comment]
It should be where you have `mongoose.connect()` instead of localhost, use a mongolab url look at https://devcenter.heroku.com/articles/mongolab#adding-mlab-as-a-heroku-add-on

and https://devcenter.heroku.com/articles/mongolab#getting-your-connection-uri

**Comment by griffind2009** [comment]
I tried doing the heroku addon via the terminal but they asked me to enter billing information.  In order to avoid this I am following the direction on this link: https://forum.freecodecamp.com/t/guide-for-using-mongodb-and-deploying-to-heroku/19347

However, I am little confused by the following steps. I am not sure if this is supposed to be in the connection file and also how it is keeping my password from being push up.

Making a Connection with MongoDB in Node.js (While DB is running in your mLab):

The url for connecting to mLab DB looks like this

var url = 'mongodb://username:password@ds01316.mlab.com:1316/food';

You can replace the url variable with this and everything will be working exactly the way it should be and finally your database is safe and secure at mLab where you can view your collections,users,backups etc..

Important Note:

But Commiting your username and password to your public repo is sometimes very dangerous so never commit them into public repositories, Instead you can use environment variables to store the url (containing username and password) , to do this in your local system

For Mac/Linux users, you can simply type:

export MONGOLAB_URI="mongodb://username:password@ds01316.mlab.com:1316/food"

For Windows users:

SET MONGOLAB_URI=mongodb://username:password@ds01316.mlab.com:1316/food

After setting the Environment variables you need to call the Environment Variable into your code. You can do it by typing this

var url = process.env.MONGOLAB_URI;

**Comment by amaseda** [comment]
What it's saying is that when you run the following line in your terminal...

`export MONGOLAB_URI="mongodb://username:password@ds01316.mlab.com:1316/food"`

You can then reference that value in your code by writing `process.env.MONGOLAB_URI`. You would use that when defining what database your app is going to connect to (i.e., `mongoose.connect`).

By doing it this way, the `MONGOLAB_URI` is only available locally and would not be pushed up to Github.

**Comment by griffind2009** [comment]
where it says "username:password@ds01316" do i enter my username and password?

**Comment by amaseda** [comment]
I assume so!

**Comment by griffind2009** [comment]
When I type that in the terminal with my username and password nothing happens? I followed the directions, I think, but nothing is happening.

**Comment by amaseda** [comment]
You shouldn't see anything after typing it into the terminal. But now try logging `process.env.MONGOLAB_URI` somewhere in your code. Does the that `mongodb://` string show up? If so, you can now use it in `mongoose.connect`.

**Comment by griffind2009** [comment]
Yes, it says "app listening on port 4000 Connection established to mongodb://localhost:27017/smalltalk connected to mongodb" in the terminal.

**Comment by amaseda** [comment]
First test to see if you can do `console.log(process.env.MONGOLAB_URI)` in your code. You can do this in the connection file if you'd like. The point here is to make sure that we can access the environment variable properly (i.e., the result of running `export MONGOLAB_URI="mongodb://username:password@ds01316.mlab.com:1316/databasename"` in the terminal).

If you can access that variable, that means you can replace the URL inside of `mongoose.connect` that currently uses localhost.

This all assumes, however, that you have created a database with mongolab.

**Comment by griffind2009** [comment]
When I console.log process.env.MONGOLAB_URI I get undefined. I'm still working on pinpointing the error

**Comment by amaseda** [comment]
The alternative is to create a separate JS file that contains the URL, `module.exports` that string from the file and then require it in your `connection.js`. You'll need to make sure you add that new file to `.gitignore` so that it's not pushed up to Github.

**Comment by griffind2009** [comment]
I still can't get it to work. Is it ok if I deploy it with gh-pages?

**Comment by amaseda** [comment]
You can only deploy static files / your front-end to gh-pages. You would need something like Heroku for your back end.

What problems are you running into exactly? Have you gotten it to work by just hardcoding the mLab address (username, password and all) in your code?

**Comment by jshawl** [comment]
try locally: `$ heorku config:get MONGOLAB_URI`

**Comment by griffind2009** [comment]
Thu Dec 01 09:08:32 ~/wdi/projects/small_talk (test *)
$ heroku config:get MONGOLAB_URI

  Thu Dec 01 09:08:56 ~/wdi/projects/small_talk (test *)
$ heroku config:set MONGOLAB_URI=mongodb://username:password@ds117348.mlab.com:17348/smalltalk
Setting MONGOLAB_URI and restarting ⬢ small-talk-for-introverts... done, v6
MONGOLAB_URI: mongodb://username:password@ds117348.mlab.com:17348/smalltalk

**Comment by jshawl** [comment]
excellent!

now back in your code:

```js
mongoose.connect(process.env.MONGOLAB_URI || 'mongodb:// ... ')
```

**Comment by griffind2009** [comment]
Cool, I did that and when I enter 'heroku config:get MONGOLAB_URI' it gives back the url for connecting to the database. I then did heroku config:set to restart, but when i refreshed my page nothing changed.

**Comment by jshawl** [comment]
did you push your code once you made the code change i suggested above? `git push heroku master`

**Comment by griffind2009** [comment]
yes

**Comment by jshawl** [comment]
what do you see when you visit your heroku url?

**Comment by jshawl** [comment]
if it's still application error - what do the logs look like? `heroku logs`

**Comment by griffind2009** [comment]
These are the errors from heroku logs

2016-12-01T14:48:31.633894+00:00 heroku[web.1]: Restarting
2016-12-01T14:48:31.635488+00:00 heroku[web.1]: State changed from up to starting
2016-12-01T14:48:32.370106+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/api/topics" host=small-talk-for-introverts.herokuapp.com request_id=eab72fc6-0ecd-4409-8e8a-b61cb7117d75 fwd="50.200.196.50" dyno=web.1 connect=0ms service=28686ms status=503 bytes=0
2016-12-01T14:48:32.346627+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-12-01T14:48:32.495013+00:00 heroku[web.1]: Process exited with status 143
2016-12-01T14:48:32.372762+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/api/questions" host=small-talk-for-introverts.herokuapp.com request_id=08277c88-2175-4477-8b44-a4349865a5dc fwd="50.200.196.50" dyno=web.1 connect=0ms service=28696ms status=503 bytes=0
2016-12-01T14:48:33.900256+00:00 heroku[web.1]: Starting process with command `npm start`
2016-12-01T14:48:36.957532+00:00 app[web.1]: 
2016-12-01T14:48:36.957543+00:00 app[web.1]: > small_talk@1.0.0 start /app
2016-12-01T14:48:36.957544+00:00 app[web.1]: > node index.js
2016-12-01T14:48:36.957545+00:00 app[web.1]: 
2016-12-01T14:48:37.883550+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-01T14:48:37.883551+00:00 app[web.1]:     at Pool.emit (events.js:188:7)
2016-12-01T14:48:37.866417+00:00 app[web.1]: app listening on port 4000
2016-12-01T14:48:37.883552+00:00 app[web.1]:     at Connection.g (events.js:291:16)
2016-12-01T14:48:37.883553+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2016-12-01T14:48:37.883549+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:313:35)
2016-12-01T14:48:37.883546+00:00 app[web.1]: Unable to connect to the mongoDB server. Error: { MongoError: failed to connect to server [localhost:27017] on first connect
2016-12-01T14:48:37.883552+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:271:12)
2016-12-01T14:48:37.883553+00:00 app[web.1]:     at Connection.emit (events.js:191:7)
2016-12-01T14:48:37.883554+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:165:49)
2016-12-01T14:48:37.883555+00:00 app[web.1]:     at Socket.g (events.js:291:16)
2016-12-01T14:48:37.883556+00:00 app[web.1]:     at emitErrorNT (net.js:1276:8)
2016-12-01T14:48:37.883555+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-01T14:48:37.883556+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2016-12-01T14:48:37.883557+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-12-01T14:48:37.883559+00:00 app[web.1]:   name: 'MongoError',
2016-12-01T14:48:37.883560+00:00 app[web.1]:   message: 'failed to connect to server [localhost:27017] on first connect' }
2016-12-01T14:48:37.883558+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-01T14:48:38.199255+00:00 app[web.1]: connected to mongodb
2016-12-01T14:48:38.668838+00:00 heroku[web.1]: State changed from starting to up

**Comment by griffind2009** [comment]
When I visit the heroku url I can see all of my html and css just not the data

**Comment by jshawl** [comment]
ok this is good! have you seeded?

**Comment by griffind2009** [comment]
oh not today

**Comment by jshawl** [comment]
try it again!

**Comment by griffind2009** [comment]
ok, i just did.  is this a problem that it didn't connect on the first try?
heroku run node db/seed.js
Running node db/seed.js on ⬢ small-talk-for-introverts... up, run.6845 (Free)
Unable to connect to the mongoDB server. Error: { MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:271:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:165:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect' }
connected to mongodb

**Comment by jshawl** [comment]
>Unable to connect to the mongoDB server. Error: { MongoError: failed to connect to server [localhost:27017] on first connect

tells me you need to use the mongolab uri - can i see your seed file?

**Comment by griffind2009** [comment]
I just refreshed and it's working! Is that command: heroku run node db/seed.js something I need to put in the readme or procfile? After all of that I'm a little confused and not sure what I need to run or tell people to run in order for the app to run.

**Comment by griffind2009** [comment]
![screen shot 2016-12-01 at 9 59 55 am](https://cloud.githubusercontent.com/assets/20979785/20798475/f83d4e20-b7ac-11e6-8909-f085783466a3.png)

![screen shot 2016-12-01 at 10 00 07 am](https://cloud.githubusercontent.com/assets/20979785/20798489/fb893e5e-b7ac-11e6-9d4e-e5db86c593da.png)

**Comment by jshawl** [comment]
>After all of that I'm a little confused and not sure what I need to run or tell people to run in order for the app to run.

You only need to seed the first time you deploy

**Comment by griffind2009** [comment]
Ok, great

**Comment by jshawl** [comment]
👍
