### ISSUE TITLE
Issue with Deployment 

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project4#366]
After successfully deploying yesterday.  I added more functionality where my project now sends SMS txt messages using TextMagic.  To install the new library locally I ran the following:

`npm install textmagic-rest-client
`
This was from the instructions https://www.textmagic.com/docs/api/node-js/

On Heroku I ran the following:
```

$ heroku run npm install textmagic-rest-client
Running npm install textmagic-rest-client on ⬢ wx-stn-be... up, run.5076 (Free)
socketio@1.0.0 /app
`-- textmagic-rest-client@0.0.5
  `-- lodash@3.10.1

npm WARN socketio@1.0.0 No repository field.
  Wed Nov 30 16:31:14 /users/MICHAELS_MAC/wdi/projects/project4/mikewxstn (master)
```

I pushed up my code and it will not run giving me this error:

2016-11-30T21:37:28.735100+00:00 heroku[web.1]: State changed from crashed to starting
2016-11-30T21:37:31.298719+00:00 heroku[web.1]: Starting process with command `npm start`
2016-11-30T21:37:34.574885+00:00 app[web.1]: 
2016-11-30T21:37:34.574901+00:00 app[web.1]: > socketio@1.0.0 start /app
2016-11-30T21:37:34.574902+00:00 app[web.1]: > node index.js
2016-11-30T21:37:34.574903+00:00 app[web.1]: 
2016-11-30T21:37:34.751916+00:00 app[web.1]: rubin_channel = 176785
2016-11-30T21:37:34.754894+00:00 app[web.1]: text_magic_api_key= J8HNQDzOVHjmK5Zprz4rpyNfjgIwna
2016-11-30T21:37:34.755295+00:00 app[web.1]: rubin_notify_phone= +17036249243
2016-11-30T21:37:35.186607+00:00 app[web.1]: module.js:471
2016-11-30T21:37:35.186620+00:00 app[web.1]:     throw err;
2016-11-30T21:37:35.186621+00:00 app[web.1]:     ^
2016-11-30T21:37:35.186621+00:00 app[web.1]: 
2016-11-30T21:37:35.186622+00:00 app[web.1]: Error: Cannot find module 'textmagic-rest-client'
2016-11-30T21:37:35.186623+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2016-11-30T21:37:35.186624+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2016-11-30T21:37:35.186625+00:00 app[web.1]:     at Module.require (module.js:497:17)
2016-11-30T21:37:35.186625+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-11-30T21:37:35.186626+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:23:16)
2016-11-30T21:37:35.186626+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2016-11-30T21:37:35.186627+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2016-11-30T21:37:35.186628+00:00 app[web.1]:     at Module.load (module.js:487:32)
2016-11-30T21:37:35.186628+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2016-11-30T21:37:35.186629+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2016-11-30T21:37:35.218007+00:00 app[web.1]: 
2016-11-30T21:37:35.238370+00:00 app[web.1]: npm ERR! Linux 3.13.0-100-generic
2016-11-30T21:37:35.238797+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-11-30T21:37:35.239341+00:00 app[web.1]: npm ERR! node v6.9.1
2016-11-30T21:37:35.239653+00:00 app[web.1]: npm ERR! npm  v3.10.8
2016-11-30T21:37:35.240129+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-11-30T21:37:35.240391+00:00 app[web.1]: npm ERR! socketio@1.0.0 start: `node index.js`
2016-11-30T21:37:35.240737+00:00 app[web.1]: npm ERR! Exit status 1
2016-11-30T21:37:35.241067+00:00 app[web.1]: npm ERR! 
2016-11-30T21:37:35.241316+00:00 app[web.1]: npm ERR! Failed at the socketio@1.0.0 start script 'node index.js'.
2016-11-30T21:37:35.241530+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-11-30T21:37:35.242321+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the socketio package,
2016-11-30T21:37:35.242530+00:00 app[web.1]: npm ERR! not with npm itself.
2016-11-30T21:37:35.242790+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-11-30T21:37:35.243000+00:00 app[web.1]: npm ERR!     node index.js
2016-11-30T21:37:35.243687+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-11-30T21:37:35.243862+00:00 app[web.1]: npm ERR!     npm bugs socketio
2016-11-30T21:37:35.244026+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-11-30T21:37:35.244210+00:00 app[web.1]: npm ERR!     npm owner ls socketio
2016-11-30T21:37:35.244364+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-11-30T21:37:35.249696+00:00 app[web.1]: 
2016-11-30T21:37:35.249973+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-11-30T21:37:35.250111+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-11-30T21:37:35.365568+00:00 heroku[web.1]: State changed from starting to crashed
2016-11-30T21:37:35.376593+00:00 heroku[web.1]: Process exited with status 1

I did send a note to TextMagic Customer support but I am awaiting an answer.

**Comment by amaseda** [comment]
Is `textmagic-rest-client` definitely listed as a dependency in `package.json`? If not, `npm install --save` it then push your code up. (I would also just push up the latest version of `package.json` just in case.)

**Comment by amaseda** [comment]
Based on our convo IRL you fixed this! Feel free to re-open if you have more questions / comments.
