### ISSUE TITLE
'Cannot Get/' when page is refreshed

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project4#381]
https://small-talk-for-introverts.herokuapp.com/

I implemented the html5Mode and added locationProvider and urlProvider to config and my router function., so I can now go to my app without the #.  The problem is when I refresh the page for '/questions' and '/topics' I get the cannot get /.  

In my layout.hbs file I have '  <base href="/" />'. 

Here is the code from my app.js file. I looked on stackoverflow and other sites and they have the same code.  Could the issue be with express, my index.js file?

![screen shot 2016-12-01 at 2 59 31 pm](https://cloud.githubusercontent.com/assets/20979785/20810210/cebb3736-b7d6-11e6-855b-fc424430b30f.png)

![screen shot 2016-12-01 at 2 59 23 pm](https://cloud.githubusercontent.com/assets/20979785/20810211/d32d0bc8-b7d6-11e6-9905-c22e3c26f51d.png)

![screen shot 2016-12-01 at 2 59 16 pm](https://cloud.githubusercontent.com/assets/20979785/20810215/d70760e0-b7d6-11e6-8c19-e60754353e27.png)

**Comment by jshawl** [comment]
can I see your server side code?

**Comment by griffind2009** [comment]
![screen shot 2016-12-01 at 3 05 53 pm](https://cloud.githubusercontent.com/assets/20979785/20810423/b96766b0-b7d7-11e6-8301-50a5cd81dc6e.png)

![screen shot 2016-12-01 at 3 06 05 pm](https://cloud.githubusercontent.com/assets/20979785/20810422/b738839c-b7d7-11e6-8137-119dfc4a9e79.png)

**Comment by jshawl** [comment]
ohhhh where you have `app.get("/*")` add a question mark `app.get("/*?")`

you can verify this by visiting `/` in a browser

**Comment by griffind2009** [comment]
When I go to '/' in a browser should it direct me to 'index of /' ?

**Comment by jshawl** [comment]
no.... i meant `http://localhost:3000/`

**Comment by griffind2009** [comment]
ohhh ok. when i go to local host i have an XMLHttpRequest cross origin error and a GET error in the console. When I go to '/' on localhost it does refresh.

**Comment by jshawl** [comment]
progress! I think you need to enable cors - http://enable-cors.org/server_expressjs.html

**Comment by griffind2009** [comment]
I added that but got an application error. So i checked heroku logs.  From what I can tell it looks there is an issue with GET and the path '/'

I added this to my code and then the argument 'next' to each http request. 
![screen shot 2016-12-01 at 3 39 57 pm](https://cloud.githubusercontent.com/assets/20979785/20811651/87a508da-b7dc-11e6-8394-f7d7b4545574.png)


2016-12-01T20:34:11.696357+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=b9d86f66-469f-4ba4-b941-436a99b485f8 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T20:34:12.127111+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=0d0e536a-eaa3-4db5-a901-aa6e277565be fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T20:34:14.979196+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=cc5bcf2e-65ce-41a9-9f70-02e4756ae814 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T20:35:29.423864+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=d51ab011-6c9c-4177-af85-9c1c5bf7e091 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T20:35:31.858844+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=8f7dc51a-5335-434d-9da2-a0053e429026 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T20:36:03.612625+00:00 heroku[slug-compiler]: Slug compilation started
2016-12-01T20:36:03.612634+00:00 heroku[slug-compiler]: Slug compilation finished
2016-12-01T20:36:04.385265+00:00 heroku[web.1]: State changed from crashed to starting
2016-12-01T20:36:06.675104+00:00 heroku[web.1]: Starting process with command `npm start`
2016-12-01T20:36:10.011050+00:00 app[web.1]: > small_talk@1.0.0 start /app
2016-12-01T20:36:10.011037+00:00 app[web.1]: 
2016-12-01T20:36:10.011051+00:00 app[web.1]: > node index.js
2016-12-01T20:36:10.011052+00:00 app[web.1]: 
2016-12-01T20:36:10.759165+00:00 app[web.1]: app listening on port 4000
2016-12-01T20:36:10.774307+00:00 app[web.1]: Unable to connect to the mongoDB server. Error: { MongoError: failed to connect to server [localhost:27017] on first connect
2016-12-01T20:36:10.774310+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:313:35)
2016-12-01T20:36:10.774312+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-01T20:36:10.774313+00:00 app[web.1]:     at Pool.emit (events.js:188:7)
2016-12-01T20:36:10.774314+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:271:12)
2016-12-01T20:36:10.774314+00:00 app[web.1]:     at Connection.g (events.js:291:16)
2016-12-01T20:36:10.774315+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2016-12-01T20:36:10.774316+00:00 app[web.1]:     at Connection.emit (events.js:191:7)
2016-12-01T20:36:10.774317+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:165:49)
2016-12-01T20:36:10.774318+00:00 app[web.1]:     at Socket.g (events.js:291:16)
2016-12-01T20:36:10.774319+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2016-12-01T20:36:10.774320+00:00 app[web.1]:     at emitErrorNT (net.js:1276:8)
2016-12-01T20:36:10.774318+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-01T20:36:10.774320+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-12-01T20:36:10.774321+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-01T20:36:10.774322+00:00 app[web.1]:   name: 'MongoError',
2016-12-01T20:36:10.774323+00:00 app[web.1]:   message: 'failed to connect to server [localhost:27017] on first connect' }
2016-12-01T20:36:11.059190+00:00 app[web.1]: connected to mongodb
2016-12-01T20:37:07.077246+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-12-01T20:37:07.077246+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-12-01T20:37:07.241303+00:00 heroku[web.1]: Process exited with status 137
2016-12-01T20:37:07.247559+00:00 heroku[web.1]: State changed from starting to crashed
2016-12-01T20:37:10.004926+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=18f91bf9-5cbe-4576-8f8d-c69e406e1bec fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T20:37:16.306642+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=f8e82dc0-7304-4b7f-b6fb-56023f9ec1f4 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T20:37:19.014629+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=2d4db743-7cb5-47b5-b2f9-6b8f0730273c fwd="50.200.196.50" dyno= connect= service= status=503 bytes=

**Comment by jshawl** [comment]
>Unable to connect to the mongoDB server. Error: { MongoError: failed to connect to server [localhost:27017] on first connect

it looks like you are trying to connect to localhost for mongo server

**Comment by griffind2009** [comment]
I am still getting the application error. I went to heroku and did a rollback to my last deployment 6 hours ago and the app is working.  However, I push any changes to heroku it goes back to not working even though all the code is the same and i just deleted and console.log.  Also, the rollback version has my old code, such console.log still showing up. I'm not sure how to get my code and heroku on the same page again?

**Comment by jshawl** [comment]
yeah that's ok go ahead and roll forward by pushing

**Comment by jshawl** [comment]
let's keep working through this!

**Comment by griffind2009** [comment]
ok, i pushed and everything is the same as it was earlier today when it was working, but now i have application error. I'm trying pinpoint the error, but having trouble.

**Comment by jshawl** [comment]
ok what is the output of `heroku logs`

**Comment by griffind2009** [comment]
```
016-12-01T21:27:59.957654+00:00 heroku[slug-compiler]: Slug compilation started
2016-12-01T21:27:59.957663+00:00 heroku[slug-compiler]: Slug compilation finished
2016-12-01T21:28:00.075922+00:00 heroku[web.1]: Restarting
2016-12-01T21:28:00.076443+00:00 heroku[web.1]: State changed from up to starting
2016-12-01T21:28:00.830900+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-12-01T21:28:00.988647+00:00 heroku[web.1]: Process exited with status 143
2016-12-01T21:28:03.132251+00:00 heroku[web.1]: Starting process with command `npm start`
2016-12-01T21:28:06.759603+00:00 app[web.1]: 
2016-12-01T21:28:06.759616+00:00 app[web.1]: > small_talk@1.0.0 start /app
2016-12-01T21:28:06.759617+00:00 app[web.1]: > node index.js
2016-12-01T21:28:06.759618+00:00 app[web.1]: 
2016-12-01T21:28:08.365611+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:313:35)
2016-12-01T21:28:08.336062+00:00 app[web.1]: app listening on port 4000
2016-12-01T21:28:08.365608+00:00 app[web.1]: Unable to connect to the mongoDB server. Error: { MongoError: failed to connect to server [localhost:27017] on first connect
2016-12-01T21:28:08.365613+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-01T21:28:08.365616+00:00 app[web.1]:     at Connection.emit (events.js:191:7)
2016-12-01T21:28:08.365614+00:00 app[web.1]:     at Pool.emit (events.js:188:7)
2016-12-01T21:28:08.365614+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:271:12)
2016-12-01T21:28:08.365615+00:00 app[web.1]:     at Connection.g (events.js:291:16)
2016-12-01T21:28:08.365616+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2016-12-01T21:28:08.365619+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2016-12-01T21:28:08.365617+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:165:49)
2016-12-01T21:28:08.365618+00:00 app[web.1]:     at Socket.g (events.js:291:16)
2016-12-01T21:28:08.365619+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-01T21:28:08.365620+00:00 app[web.1]:     at emitErrorNT (net.js:1276:8)
2016-12-01T21:28:08.365621+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-12-01T21:28:08.365622+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-01T21:28:08.365622+00:00 app[web.1]:   name: 'MongoError',
2016-12-01T21:28:08.365623+00:00 app[web.1]:   message: 'failed to connect to server [localhost:27017] on first connect' }
2016-12-01T21:28:08.956942+00:00 app[web.1]: connected to mongodb
2016-12-01T21:29:03.678210+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-12-01T21:29:03.678328+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-12-01T21:29:03.817698+00:00 heroku[web.1]: Process exited with status 137
2016-12-01T21:29:03.831696+00:00 heroku[web.1]: State changed from starting to crashed
2016-12-01T21:29:03.832680+00:00 heroku[web.1]: State changed from crashed to starting
2016-12-01T21:29:05.387784+00:00 heroku[web.1]: Starting process with command `npm start`
2016-12-01T21:29:07.885433+00:00 app[web.1]: 
2016-12-01T21:29:07.885445+00:00 app[web.1]: > node index.js
2016-12-01T21:29:07.885444+00:00 app[web.1]: > small_talk@1.0.0 start /app
2016-12-01T21:29:07.885446+00:00 app[web.1]: 
2016-12-01T21:29:08.489976+00:00 app[web.1]: app listening on port 4000
2016-12-01T21:29:08.504402+00:00 app[web.1]: Unable to connect to the mongoDB server. Error: { MongoError: failed to connect to server [localhost:27017] on first connect
2016-12-01T21:29:08.504404+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:313:35)
2016-12-01T21:29:08.504405+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-01T21:29:08.504406+00:00 app[web.1]:     at Pool.emit (events.js:188:7)
2016-12-01T21:29:08.504406+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:271:12)
2016-12-01T21:29:08.504407+00:00 app[web.1]:     at Connection.g (events.js:291:16)
2016-12-01T21:29:08.504407+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2016-12-01T21:29:08.504408+00:00 app[web.1]:     at Connection.emit (events.js:191:7)
2016-12-01T21:29:08.504408+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:165:49)
2016-12-01T21:29:08.504408+00:00 app[web.1]:     at Socket.g (events.js:291:16)
2016-12-01T21:29:08.504409+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-12-01T21:29:08.504409+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2016-12-01T21:29:08.504410+00:00 app[web.1]:     at emitErrorNT (net.js:1276:8)
2016-12-01T21:29:08.504410+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-12-01T21:29:08.504411+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-01T21:29:08.504411+00:00 app[web.1]:   name: 'MongoError',
2016-12-01T21:29:08.504412+00:00 app[web.1]:   message: 'failed to connect to server [localhost:27017] on first connect' }
2016-12-01T21:29:08.712482+00:00 app[web.1]: connected to mongodb
2016-12-01T21:29:27.297301+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/api/questions" host=small-talk-for-introverts.herokuapp.com request_id=11bc75a9-d627-4e8f-b8c0-de213b720e97 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T21:29:29.288156+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/api/questions" host=small-talk-for-introverts.herokuapp.com request_id=2e739b7a-dc7f-459f-b0f2-d6edfaab6409 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T21:29:29.310745+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/api/topics" host=small-talk-for-introverts.herokuapp.com request_id=9f7c4d87-49e2-4243-a537-cb98086cd891 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T21:29:30.771944+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=4a115dfc-5c06-4ddc-8b90-826e117a0774 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T21:30:05.812078+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-12-01T21:30:05.812200+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-12-01T21:30:05.968400+00:00 heroku[web.1]: Process exited with status 137
2016-12-01T21:30:05.955307+00:00 heroku[web.1]: State changed from starting to crashed
2016-12-01T21:30:06.475631+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=ed347064-8daf-4ee8-9e81-af176f908f5c fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T21:30:08.705928+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=145bd41c-5ed2-4b3c-b916-d8437d8c3c99 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
2016-12-01T21:31:04.206954+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=small-talk-for-introverts.herokuapp.com request_id=81665639-a86b-4278-ac48-c88c57bff7ea fwd="50.200.196.50" dyno= connect= service= status=503 bytes=

```

**Comment by jshawl** [comment]
ok this is the error

>Unable to connect to the mongoDB server.

**Comment by jshawl** [comment]
can i see `mongo.connect()` in your application?

**Comment by griffind2009** [comment]
mongoose.connect(process.env.MONGOLAB_URI || 'mongodb://localhost:27017/smalltalk')

**Comment by jshawl** [comment]
ok promising!

what is the output of `heroku config`

**Comment by griffind2009** [comment]
$ heroku config
=== small-talk-for-introverts Config Vars
MONGOLAB_URI: mongodb://myusername:mypassword@ds117348.mlab.com:17348/smalltalk

**Comment by jshawl** [comment]
ok this looks good - did you commit and push to heroku?

**Comment by griffind2009** [comment]
I last deployed about 40 mins ago

**Comment by jshawl** [comment]
ok try pushing again

**Comment by griffind2009** [comment]
It says everything is up to date. the application error is still showing when i go to the apps url

**Comment by jshawl** [comment]
omg what. and you're pushhing to heroku?

**Comment by griffind2009** [comment]
i think so

$ git push heroku master
Everything up-to-date

**Comment by jshawl** [comment]
and your working directory is clean? `git status`?

and your mongoose.connect references the mongolab uri?

**Comment by griffind2009** [comment]
This what i have from nodemon 
app listening on port 4000
Connection established to mongodb://localhost:27017/smalltalk
connected to mongodb

**Comment by griffind2009** [comment]
directory is up to date

**Comment by jshawl** [comment]
I still see localhost in your code - https://github.com/griffind2009/Project4/blob/master/db/connection.js#L5

shouldn't it be process.env...?

**Comment by griffind2009** [comment]
so instead of: mongoose.connect (process.env.MONGOLAB_URI || 'mongodb://localhost:27017/smalltalk')

it should be mongoose.connect(process.env.MONGOLAB_URI || 'mongodb://process.env.MONGOLAB_URI/smalltalk'

?

**Comment by griffind2009** [comment]
When I login to mLab I can see that my database is connected and all the data is there

**Comment by jshawl** [comment]
no sorry. do you mind pushing your code to github so i can try deploying the same code that you have?

**Comment by griffind2009** [comment]
cool, i just pushed it

**Comment by jshawl** [comment]
are you working on a different branch? https://github.com/griffind2009/Project4/blob/master/db/connection.js#L5

**Comment by griffind2009** [comment]
No, the master branch. Is that line of code incorrect?

**Comment by jshawl** [comment]
yes - you need to use `process.env` instead of localhost

**Comment by griffind2009** [comment]
oh ok, it's fixed.

**Comment by jshawl** [comment]
excellent! 👍

**Comment by griffind2009** [comment]
oh sorry i meant i fixed that line of code.
