### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project4#454]
Hello, here is the link to my repo: https://github.com/nrc0004/project4

I'm currently trying  to seed my database and I am getting the following error when I try to run node db/seeds.js: 

/Users/natashaclark/wdi/project/project4/db/models.js:19
  Exercise
  ^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/natashaclark/wdi/project/project4/db/seeds.js:2:17)
    at Module._compile (module.js:571:32)

**Comment by amaseda** [comment]
You need a comma in that `module.exports` statement to separate `Program` and `Exercise`

**Comment by nrc0004** [comment]
Omg… I’ve literally been looking at that for like 20 minutes….

Thank you

**Comment by amaseda** [comment]
No problem!
