### ISSUE TITLE
Heroku Build not working

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project4#462]
I tried to deploy what I have to heroku, and after specifying the engine and start script, the build log shows no errors:
```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  7.4.0
       engines.npm (package.json):   unspecified (use default)
       
       Downloading and installing node 7.4.0...
       Using default npm version: 4.0.5
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (package.json)
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 21.3M
-----> Launching...
       Released v5
       https://watsons-diary.herokuapp.com/ deployed to Heroku
```
Here is my `package.json`:
```
{
  "name": "watson_node2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.17.1",
    "chart.js": "^2.5.0",
    "dotenv": "^4.0.0",
    "express": "^4.15.2",
    "express-handlebars": "^3.0.0",
    "jquery": "^3.2.1",
    "jsdom": "^9.12.0"
  },
  "engines": {
    "node": "7.4.0"
  }
}
```
Here is the repo: https://github.com/justwes2/watsons-diary
Any idea what I am doing wrong or how to debug with a clean log?

**Comment by superbuggy** [comment]
what is the output of `heroku logs`?

**Comment by justwes2** [comment]
```
2017-04-05T13:42:22.000000+00:00 app[api]: Build started by user wes.coffay@gmail.com
2017-04-05T13:42:37.208852+00:00 app[api]: Release v5 created by user wes.coffay@gmail.com
2017-04-05T13:42:37.208852+00:00 app[api]: Deploy 1bf340e by user wes.coffay@gmail.com
2017-04-05T13:42:22.000000+00:00 app[api]: Build succeeded
2017-04-05T13:42:38.741641+00:00 app[api]: Release v5 created by user wes.coffay@gmail.com
2017-04-05T13:42:39.408398+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-05T13:42:41.636486+00:00 heroku[web.1]: Starting process with command `npm start`
2017-04-05T13:42:44.347513+00:00 app[web.1]: 
2017-04-05T13:42:44.347513+00:00 app[web.1]: > node server.js
2017-04-05T13:42:44.347500+00:00 app[web.1]: 
2017-04-05T13:42:44.398539+00:00 app[web.1]: module.js:472
2017-04-05T13:42:44.347512+00:00 app[web.1]: > watson_node2@1.0.0 start /app
2017-04-05T13:42:44.398543+00:00 app[web.1]:     throw err;
2017-04-05T13:42:44.398544+00:00 app[web.1]:     ^
2017-04-05T13:42:44.398545+00:00 app[web.1]: 
2017-04-05T13:42:44.398545+00:00 app[web.1]: Error: Cannot find module '/app/server.js'
2017-04-05T13:42:44.398547+00:00 app[web.1]:     at Function.Module._load (module.js:418:25)
2017-04-05T13:42:44.398548+00:00 app[web.1]:     at Module.runMain (module.js:605:10)
2017-04-05T13:42:44.398546+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:470:15)
2017-04-05T13:42:44.398548+00:00 app[web.1]:     at run (bootstrap_node.js:420:7)
2017-04-05T13:42:44.398549+00:00 app[web.1]:     at startup (bootstrap_node.js:139:9)
2017-04-05T13:42:44.405004+00:00 app[web.1]: 
2017-04-05T13:42:44.398550+00:00 app[web.1]:     at bootstrap_node.js:535:3
2017-04-05T13:42:44.412029+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-04-05T13:42:44.412205+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-04-05T13:42:44.412393+00:00 app[web.1]: npm ERR! node v7.4.0
2017-04-05T13:42:44.412515+00:00 app[web.1]: npm ERR! npm  v4.0.5
2017-04-05T13:42:44.412648+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-04-05T13:42:44.412879+00:00 app[web.1]: npm ERR! watson_node2@1.0.0 start: `node server.js`
2017-04-05T13:42:44.412967+00:00 app[web.1]: npm ERR! Exit status 1
2017-04-05T13:42:44.413099+00:00 app[web.1]: npm ERR! 
2017-04-05T13:42:44.413189+00:00 app[web.1]: npm ERR! Failed at the watson_node2@1.0.0 start script 'node server.js'.
2017-04-05T13:42:44.413311+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-04-05T13:42:44.413415+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the watson_node2 package,
2017-04-05T13:42:44.413503+00:00 app[web.1]: npm ERR! not with npm itself.
2017-04-05T13:42:44.413597+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-04-05T13:42:44.413681+00:00 app[web.1]: npm ERR!     node server.js
2017-04-05T13:42:44.413852+00:00 app[web.1]: npm ERR!     npm bugs watson_node2
2017-04-05T13:42:44.413766+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-04-05T13:42:44.413926+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-04-05T13:42:44.414012+00:00 app[web.1]: npm ERR!     npm owner ls watson_node2
2017-04-05T13:42:44.418003+00:00 app[web.1]: 
2017-04-05T13:42:44.414085+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-04-05T13:42:44.418240+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-04-05T13:42:44.418384+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-04-05T13:42:44.482052+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-05T13:42:44.490527+00:00 heroku[web.1]: Process exited with status 1
2017-04-05T13:42:45.440055+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=watsons-diary.herokuapp.com request_id=69dbbc7e-e3a4-4f8c-988d-f6291365e49d fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-05T13:42:45.610677+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=watsons-diary.herokuapp.com request_id=abcd257d-7423-493a-a0a8-58352d5c8ade fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-05T13:44:34.462467+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=watsons-diary.herokuapp.com request_id=2971740b-9f0e-4857-93c3-e04a17f128e3 fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-05T13:44:34.646899+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=watsons-diary.herokuapp.com request_id=554eb154-beea-4b0f-86b1-de28c7ba054d fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-05T13:54:26.494654+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-05T13:54:31.546628+00:00 heroku[web.1]: Starting process with command `npm start`
2017-04-05T13:54:34.282112+00:00 app[web.1]: 
2017-04-05T13:54:34.282133+00:00 app[web.1]: > watson_node2@1.0.0 start /app
2017-04-05T13:54:34.282135+00:00 app[web.1]: 
2017-04-05T13:54:34.332978+00:00 app[web.1]: module.js:472
2017-04-05T13:54:34.332985+00:00 app[web.1]:     throw err;
2017-04-05T13:54:34.332987+00:00 app[web.1]: 
2017-04-05T13:54:34.282134+00:00 app[web.1]: > node server.js
2017-04-05T13:54:34.332989+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:470:15)
2017-04-05T13:54:34.332990+00:00 app[web.1]:     at Function.Module._load (module.js:418:25)
2017-04-05T13:54:34.332990+00:00 app[web.1]:     at Module.runMain (module.js:605:10)
2017-04-05T13:54:34.332986+00:00 app[web.1]:     ^
2017-04-05T13:54:34.332991+00:00 app[web.1]:     at startup (bootstrap_node.js:139:9)
2017-04-05T13:54:34.332988+00:00 app[web.1]: Error: Cannot find module '/app/server.js'
2017-04-05T13:54:34.332992+00:00 app[web.1]:     at bootstrap_node.js:535:3
2017-04-05T13:54:34.339452+00:00 app[web.1]: 
2017-04-05T13:54:34.346966+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-04-05T13:54:34.332991+00:00 app[web.1]:     at run (bootstrap_node.js:420:7)
2017-04-05T13:54:34.347265+00:00 app[web.1]: npm ERR! npm  v4.0.5
2017-04-05T13:54:34.346764+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-04-05T13:54:34.347402+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-04-05T13:54:34.347627+00:00 app[web.1]: npm ERR! watson_node2@1.0.0 start: `node server.js`
2017-04-05T13:54:34.347814+00:00 app[web.1]: npm ERR! 
2017-04-05T13:54:34.347905+00:00 app[web.1]: npm ERR! Failed at the watson_node2@1.0.0 start script 'node server.js'.
2017-04-05T13:54:34.347149+00:00 app[web.1]: npm ERR! node v7.4.0
2017-04-05T13:54:34.347980+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-04-05T13:54:34.347719+00:00 app[web.1]: npm ERR! Exit status 1
2017-04-05T13:54:34.348146+00:00 app[web.1]: npm ERR! not with npm itself.
2017-04-05T13:54:34.348319+00:00 app[web.1]: npm ERR!     node server.js
2017-04-05T13:54:34.348411+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-04-05T13:54:34.348487+00:00 app[web.1]: npm ERR!     npm bugs watson_node2
2017-04-05T13:54:34.348072+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the watson_node2 package,
2017-04-05T13:54:34.348655+00:00 app[web.1]: npm ERR!     npm owner ls watson_node2
2017-04-05T13:54:34.348244+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-04-05T13:54:34.348739+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-04-05T13:54:34.351969+00:00 app[web.1]: 
2017-04-05T13:54:34.348575+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-04-05T13:54:34.352191+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-04-05T13:54:34.352117+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-04-05T13:54:34.421092+00:00 heroku[web.1]: Process exited with status 1
2017-04-05T13:54:34.445282+00:00 heroku[web.1]: State changed from starting to crashed
```

So it looks like the problem is with the node server.js. I was unclear, what should the start script be? The docs seemed to dance around it more...

**Comment by superbuggy** [comment]
```
2017-04-05T13:42:44.398545+00:00 app[web.1]: Error: Cannot find module '/app/server.js'
```

**Comment by justwes2** [comment]
Alright, so I changed it from `server.js` to `index.js`. which is where my app runs from. I redeployed, but it still cannot find the module. Where else does that need to be defined/instantiated?

**Comment by superbuggy** [comment]
is it in a folder called `app`?

**Comment by justwes2** [comment]
No, in the root directory. Why would heroku be looking for in in a folder(I see the path, I just don't see where I specified a path)?

**Comment by justwes2** [comment]
Any thoughts on where the path name might be defined that I can edit? Or should I make an app directory to put the js file in?

**Comment by superbuggy** [comment]
It's expecting that the file lives in an directory called app by default. [Define a Procfile to override this behavior](https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-a-procfile)

**Comment by justwes2** [comment]
Alright, now I'm running into an issue where my api key is in the gitignore file. How can I make it visible to to heroku without adding it the the git repo?

**Comment by justwes2** [comment]
Got that solved. Now I'm getting an R10 error:
```
2017-04-05T15:56:04.993024+00:00 app[api]: Set DB_USER config vars by user wes.coffay@gmail.com
2017-04-05T15:56:04.993024+00:00 app[api]: Release v12 created by user wes.coffay@gmail.com
2017-04-05T15:56:05.150448+00:00 app[api]: Release v12 created by user wes.coffay@gmail.com
2017-04-05T15:56:05.223547+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-05T15:56:07.800609+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-04-05T15:56:10.785914+00:00 app[web.1]: Port 4000 open
2017-04-05T15:57:07.914449+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2017-04-05T15:57:07.914624+00:00 heroku[web.1]: Stopping process with SIGKILL
2017-04-05T15:57:08.034324+00:00 heroku[web.1]: Process exited with status 137
2017-04-05T15:57:08.047788+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-05T15:57:10.512885+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=watsons-diary.herokuapp.com request_id=29d20fe4-c2a5-4925-bd9f-1d3e08cd3120 fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-05T15:57:10.866156+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=watsons-diary.herokuapp.com request_id=35833782-1157-4434-99fc-fd5be3f63909 fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
```
meep

**Comment by amaseda** [comment]
Does this post help? https://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of

**Comment by justwes2** [comment]
cool. Next hurdle...
