### ISSUE TITLE
swapping out localhost without a database to query

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project4#469]
My current build has a front end and a back end to handle a third party api request. However, that means that the factory exists and is set to `http://localhost:4000/text`. What do I need to change that to for deployment. I tried routing it through the deployed page, but that didn't work. What is the address for the back end factory?

**Comment by amaseda** [comment]
Everything is in the same app, correct? If so, you should be able to just set `/text` as the API call's URL and it will append whatever the app's base URL is by default.

**Comment by justwes2** [comment]
Now I am getting a 503 service unavailable error. It seems like I am back to an error with the watson api: 
```
2017-04-05T17:21:23.234541+00:00 app[web.1]: error: { Error: Not Authorized
2017-04-05T17:21:23.234556+00:00 app[web.1]:     at Request._callback (/app/node_modules/watson-developer-cloud/lib/requestwrapper.js:83:15)
2017-04-05T17:21:23.234564+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/watson-developer-cloud/node_modules/request/request.js:186:22)
2017-04-05T17:21:23.234572+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-04-05T17:21:23.234573+00:00 app[web.1]:     at Request.emit (events.js:191:7)
2017-04-05T17:21:23.234574+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-05T17:21:23.234573+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/watson-developer-cloud/node_modules/request/request.js:1081:10)
2017-04-05T17:21:23.234575+00:00 app[web.1]:     at Request.emit (events.js:188:7)
2017-04-05T17:21:23.234582+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/watson-developer-cloud/node_modules/request/request.js:1001:12)
2017-04-05T17:21:23.234583+00:00 app[web.1]:     at Object.onceWrapper (events.js:290:19)
2017-04-05T17:21:23.234584+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-04-05T17:21:23.234597+00:00 app[web.1]:   code: 401,
2017-04-05T17:21:23.234598+00:00 app[web.1]:   error: 'Not Authorized',
2017-04-05T17:21:23.234605+00:00 app[web.1]:   description: '2017-04-05T13:21:23-04:00, Error ERCDPLTFRM-INVLDCHR occurred when accessing https://158.85.132.88:443/natural-language-understanding/api/v1/analyze?version=2017-02-27, Tran-Id: gateway-dp02-41876098 - ' }
2017-04-05T17:21:52.942777+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/text?text=In+the+US,+support+
```
I added the api key to heroku config, so I'm not sure where the not authorized error is coming from.

**Comment by amaseda** [comment]
Have you defined environment variables for your Heroku environment? I imagine locally you had an `env.js` that stored your API key and other sensitive information. You need to set those values in your production environment.

Here's how you would go about defining environment variables: https://devcenter.heroku.com/articles/nodejs-support#environment-variables

Here's an example of how you would go about accessing those values programmatically: https://devcenter.heroku.com/articles/config-vars#example

**Comment by justwes2** [comment]
Alright so in config they were in quotes that they should not have been. Thanks!
