### ISSUE TITLE
MERN APP deployment

### ISSUE THREAD

**Issue by evalaidc** [ga-wdi-exercises/project4#482]
Hello,

I tried deploying my mern app, but I get an error if my server isn't running as well. 

```
10:34:03 AM api.1 |  api running
10:34:03 AM api.1 |  { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
10:34:03 AM api.1 |      at Pool.<anonymous> (/Users/elai/wdi/projects/project4/mums-the-word/node_modules/mongodb-core/lib/topologies/server.js:327:35)
10:34:03 AM api.1 |      at emitOne (events.js:96:13)
10:34:03 AM api.1 |      at Pool.emit (events.js:188:7)
10:34:03 AM api.1 |      at Connection.<anonymous> (/Users/elai/wdi/projects/project4/mums-the-word/node_modules/mongodb-core/lib/connection/pool.js:274:12)
10:34:03 AM api.1 |      at Object.onceWrapper (events.js:290:19)
10:34:03 AM api.1 |      at emitTwo (events.js:106:13)
10:34:03 AM api.1 |      at Connection.emit (events.js:191:7)
10:34:03 AM api.1 |      at Socket.<anonymous> (/Users/elai/wdi/projects/project4/mums-the-word/node_modules/mongodb-core/lib/connection/connection.js:177:49)
10:34:03 AM api.1 |      at Object.onceWrapper (events.js:290:19)
10:34:03 AM api.1 |      at emitOne (events.js:96:13)
10:34:03 AM api.1 |      at Socket.emit (events.js:188:7)
10:34:03 AM api.1 |      at emitErrorNT (net.js:1281:8)
10:34:03 AM api.1 |      at _combinedTickCallback (internal/process/next_tick.js:74:11)
10:34:03 AM api.1 |      at process._tickCallback (internal/process/next_tick.js:98:9)
10:34:03 AM api.1 |    name: 'MongoError',
10:34:03 AM api.1 |    message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }
10:34:03 AM web.1 |  Starting the development server...
10:34:08 AM web.1 |  Compiled successfully!
10:34:08 AM web.1 |  The app is running at:
10:34:08 AM web.1 |    http://localhost:3001/
10:34:08 AM web.1 |  Note that the development build is not optimized.
10:34:08 AM web.1 |  To create a production build, use npm run build.
10:34:08 AM api.1 |  (node:81738) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
```

My heroku site works, but only if my server is running with it. otherwise it won't run nor depend on the MLab library.

Is there a way I can fix it so it will run on the external server and not my computer?

in my db/connection.js file, I already connected it to the MLab
```const mongoose = require('mongoose')

mongoose.connect(process.env.MONGOLAB_URI || 'mongodb://localhost/mums_the_word_db', (err, res) => {
  if(err){
    console.log(err)
  } else {
    console.log("MongoDB connected")
  }
})

const db = mongoose.connection

module.exports = mongoose
```

**Comment by amaseda** [comment]
Have you defined a MONGOLAB_URI in your development environment?

https://devcenter.heroku.com/articles/mongolab#getting-your-connection-uri

**Comment by evalaidc** [comment]
I did. and asked Nyketha, but I am still confused on when I call axios. it calls upon localhost:3101. how do we find out the api website link?

**Comment by evalaidc** [comment]
```
mongoose.connect(process.env.MONGOLAB_URI || 'mongodb://localhost/mums_the_word_db' || 'mongodb://heroku_fmbpqk9c:lk8t50talmb31ndm3i8a67qjvp@ds155490.mlab.com:55490/heroku_fmbpqk9c', (err, res) => {
  if(err){
    console.log(err)
  } else {
    console.log("MongoDB connected")
  }
})
```

I do have that in my db/connection.js but I think it might be a problem with axios and it doesn't recognize which url to pull from. 

this is in my app.js file where  i manually typed in the url.
```
            <Route
              path='/Home'
              render={() => {
                return (
                  <SpotsContainer
                  url='http://127.0.0.1:3101/api/spots'
                  interval={2000}
                  />
                )
              }}
            />
```
// this is in my SpotsContainer component where I use axios 

```
  componentDidMount() {
   this.loadSpotsFromAPI();
   setInterval(this.loadSpotsFromAPI(), this.props.interval);
   }

  loadSpotsFromAPI() {
    axios.get(this.props.url).then(res => {
      this.setState({
        data: res.data
      })
    }).catch(err => {
      console.log('api request failed')
   })
  };
```

I don't know if there is a separate url I have to connect to in order to get axios to pull from mlab instead of my local server.

**Comment by superbuggy** [comment]
Did you set up on your node environment variable as `MONGOLAB_URL` instead of `MONGOLAB_URI` with the heroku CLI?

**Comment by evalaidc** [comment]
@superbuggy 

I don't know exactly what you mean by that. i did create the database in heroku using mlabs
and set the mongoose.connection to 'mongodb://heroku_fmbpqk9c:lk8t50talmb31ndm3i8a67qjvp@ds155490.mlab.com:55490/heroku_fmbpqk9c'

but was there suppose to be a CLI command i was suppose to run?

**Comment by superbuggy** [comment]
If you haven't, try running the command below in your project dir:
```bash
$ heroku config:set MONGOLAB_URI="mongodb://heroku_fmbpqk9c:lk8t50talmb31ndm3i8a67qjvp@ds155490.mlab.com:55490/heroku_fmbpqk9c"
```

**Comment by evalaidc** [comment]
Oh i have set that up already.

Setting MONGOLAB_URI and restarting ⬢ mums-the-word... done, v17
MONGOLAB_URI: mongodb://heroku_fmbpqk9c:lk8t50talmb31ndm3i8a67qjvp@ds155490.mlab.com:55490/heroku_fmbpqk9c

this was the response I got. but i guess I am just curious what do I pull/ what is the URL for the axios database to pull from?

**Comment by superbuggy** [comment]
something like `http://mums-the-word.herokuapp.com/api/tacos`

**Comment by evalaidc** [comment]
hmmm i guess it still isn't detecting the db. 

<img width="1440" alt="screenshot 2017-04-16 19 46 23" src="https://cloud.githubusercontent.com/assets/24941303/25075228/7f0874a2-22dd-11e7-9fc9-5d8f442e70a8.png">

**Comment by superbuggy** [comment]
Is `heroku logs` indicating that you aren't connected to the db?

What if you convert all your urls to `https`?

**Comment by evalaidc** [comment]
```
2017-04-16T23:06:08.560789+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=51375f06-283b-439a-92f3-26ec12bf79cc fwd="173.66.186.124" dyno=web.1 connect=1ms service=3ms status=404 bytes=415 protocol=https
2017-04-16T23:06:08.596779+00:00 heroku[router]: at=info method=GET path="/sockjs-node/info?t=1492383964948" host=mums-the-word.herokuapp.com request_id=414bf53e-1b9d-4ff8-a66c-285551cb584a fwd="173.66.186.124" dyno=web.1 connect=0ms service=2ms status=200 bytes=363 protocol=https
2017-04-16T23:06:08.915459+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=mums-the-word.herokuapp.com request_id=6c40bddc-28d3-43c2-ac72-c5049268a575 fwd="173.66.186.124" dyno=web.1 connect=0ms service=2ms status=200 bytes=712 protocol=https
2017-04-16T23:30:34.882202+00:00 heroku[router]: at=error code=H15 desc="Idle connection" method=GET path="/sockjs-node/553/ixpoaizr/websocket" host=mums-the-word.herokuapp.com request_id=88f796ab-4383-4808-999c-df2f5396022c fwd="173.66.186.124" dyno=web.1 connect=2ms service=1466075ms status=503 bytes= protocol=https
2017-04-16T23:42:30.733505+00:00 heroku[api.1]: Idling
2017-04-16T23:42:30.734009+00:00 heroku[api.1]: State changed from up to down
2017-04-16T23:42:30.748527+00:00 heroku[web.1]: Idling
2017-04-16T23:42:30.748527+00:00 heroku[web.1]: State changed from up to down
2017-04-16T23:42:31.222461+00:00 heroku[api.1]: Stopping all processes with SIGTERM
2017-04-16T23:42:31.305125+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2017-04-16T23:42:31.385517+00:00 heroku[api.1]: Process exited with status 143
2017-04-16T23:42:31.434919+00:00 heroku[web.1]: Process exited with status 143
2017-04-16T23:42:50.589582+00:00 heroku[api.1]: Unidling
2017-04-16T23:42:50.591071+00:00 heroku[api.1]: State changed from down to starting
2017-04-16T23:42:50.633887+00:00 heroku[web.1]: Unidling
2017-04-16T23:42:50.634116+00:00 heroku[web.1]: State changed from down to starting
2017-04-16T23:42:54.744211+00:00 heroku[api.1]: Starting process with command `node src/server.js`
2017-04-16T23:42:54.992675+00:00 heroku[web.1]: Starting process with command `react-scripts start`
2017-04-16T23:42:55.274980+00:00 heroku[api.1]: State changed from starting to up
2017-04-16T23:42:57.233564+00:00 app[api.1]: api running
2017-04-16T23:42:57.436765+00:00 app[api.1]: MongoDB connected
2017-04-16T23:42:59.383119+00:00 app[web.1]: 
2017-04-16T23:42:59.382366+00:00 app[web.1]: Starting the development server...
2017-04-16T23:42:59.877619+00:00 heroku[web.1]: State changed from starting to up
2017-04-16T23:43:07.021366+00:00 app[web.1]: Compiled with warnings.
2017-04-16T23:43:07.021399+00:00 app[web.1]: 
2017-04-16T23:43:07.021500+00:00 app[web.1]: Warning in ./src/Components/App/App.js
2017-04-16T23:43:07.021501+00:00 app[web.1]: 
2017-04-16T23:43:07.021503+00:00 app[web.1]:   14:3  warning  Useless constructor  no-useless-constructor
2017-04-16T23:43:07.021502+00:00 app[web.1]: /app/src/Components/App/App.js
2017-04-16T23:43:07.021504+00:00 app[web.1]: 
2017-04-16T23:43:07.021504+00:00 app[web.1]: ✖ 1 problem (0 errors, 1 warning)
2017-04-16T23:43:07.021505+00:00 app[web.1]: 
2017-04-16T23:43:07.021549+00:00 app[web.1]: 
2017-04-16T23:43:07.021600+00:00 app[web.1]: You may use special comments to disable some warnings.
2017-04-16T23:43:07.021683+00:00 app[web.1]: Use // eslint-disable-next-line to ignore the next line.
2017-04-16T23:43:07.021755+00:00 app[web.1]: Use /* eslint-disable */ to ignore all warnings in a file.
2017-04-16T23:43:07.151784+00:00 heroku[router]: at=info method=GET path="/" host=mums-the-word.herokuapp.com request_id=8187e9b9-6faa-4fe5-bb8a-96ca331bd1ef fwd="172.56.11.6" dyno=web.1 connect=1ms service=4479ms status=200 bytes=712 protocol=http
2017-04-16T23:43:07.699033+00:00 heroku[router]: at=info method=GET path="/static/js/bundle.js" host=mums-the-word.herokuapp.com request_id=5b829646-34ae-42aa-afac-1142ff999d8c fwd="172.56.11.6" dyno=web.1 connect=1ms service=284ms status=200 bytes=301667 protocol=http
2017-04-16T23:43:12.478975+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=673244d0-4ed1-42ff-a2de-7658002a64e0 fwd="172.56.11.6" dyno=web.1 connect=1ms service=17ms status=404 bytes=415 protocol=http
2017-04-16T23:43:12.606944+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=f51c45f0-2ff9-48ce-8265-137385b9c8d9 fwd="172.56.11.6" dyno=web.1 connect=1ms service=10ms status=404 bytes=415 protocol=http
2017-04-16T23:43:13.732436+00:00 heroku[router]: at=info method=GET path="/sockjs-node/info?t=1492386193676" host=mums-the-word.herokuapp.com request_id=e9c2d9e8-d67e-402e-9178-4a5f9e1f24e7 fwd="172.56.11.6" dyno=web.1 connect=1ms service=11ms status=200 bytes=360 protocol=http
2017-04-16T23:43:33.779797+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=mums-the-word.herokuapp.com request_id=8e7ea78f-1309-4015-a8a8-b84f79b664af fwd="172.56.11.6" dyno=web.1 connect=1ms service=4ms status=200 bytes=712 protocol=http
2017-04-16T23:44:52.095722+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=af4c9ade-af2a-429d-bcc8-d39b43605d1a fwd="173.66.186.124" dyno=web.1 connect=1ms service=30ms status=404 bytes=415 protocol=http
2017-04-16T23:44:53.219392+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=50863703-78ab-4d18-a299-be5838a58625 fwd="173.66.186.124" dyno=web.1 connect=1ms service=5ms status=404 bytes=415 protocol=http
2017-04-16T23:45:09.000000+00:00 app[api]: Build started by user evalai.dc@gmail.com
2017-04-16T23:45:35.472551+00:00 app[api]: Deploy 98d7d0a by user evalai.dc@gmail.com
2017-04-16T23:45:35.472551+00:00 app[api]: Release v20 created by user evalai.dc@gmail.com
2017-04-16T23:45:09.000000+00:00 app[api]: Build succeeded
2017-04-16T23:45:35.873956+00:00 app[api]: Release v20 created by user evalai.dc@gmail.com
2017-04-16T23:45:36.187582+00:00 heroku[api.1]: Restarting
2017-04-16T23:45:36.190119+00:00 heroku[api.1]: State changed from up to starting
2017-04-16T23:45:36.250171+00:00 heroku[web.1]: Restarting
2017-04-16T23:45:36.250974+00:00 heroku[web.1]: State changed from up to starting
2017-04-16T23:45:36.729793+00:00 heroku[api.1]: Stopping all processes with SIGTERM
2017-04-16T23:45:36.825490+00:00 heroku[api.1]: Process exited with status 143
2017-04-16T23:45:36.951098+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2017-04-16T23:45:37.122346+00:00 heroku[web.1]: Process exited with status 143
2017-04-16T23:45:37.137463+00:00 heroku[router]: at=info method=GET path="/sockjs-node/248/0u21ca3g/websocket" host=mums-the-word.herokuapp.com request_id=26b314c1-4a49-4117-850b-a8b8b31cd0b3 fwd="172.56.11.6" dyno=web.1 connect=1ms service=142229ms status=101 bytes=129 protocol=http
2017-04-16T23:45:40.590373+00:00 heroku[web.1]: Starting process with command `react-scripts start`
2017-04-16T23:45:40.643447+00:00 heroku[api.1]: Starting process with command `node src/server.js`
2017-04-16T23:45:41.289292+00:00 heroku[api.1]: State changed from starting to up
2017-04-16T23:45:44.006485+00:00 app[api.1]: api running
2017-04-16T23:45:44.430214+00:00 app[web.1]: Starting the development server...
2017-04-16T23:45:44.431020+00:00 app[web.1]: 
2017-04-16T23:45:44.514226+00:00 app[api.1]: MongoDB connected
2017-04-16T23:45:45.107503+00:00 heroku[web.1]: State changed from starting to up
2017-04-16T23:45:53.638585+00:00 app[web.1]: Compiled with warnings.
2017-04-16T23:45:53.638800+00:00 app[web.1]: Warning in ./src/Components/App/App.js
2017-04-16T23:45:53.638675+00:00 app[web.1]: 
2017-04-16T23:45:53.638802+00:00 app[web.1]: 
2017-04-16T23:45:53.638802+00:00 app[web.1]: /app/src/Components/App/App.js
2017-04-16T23:45:53.638804+00:00 app[web.1]:   14:3  warning  Useless constructor  no-useless-constructor
2017-04-16T23:45:53.638805+00:00 app[web.1]: 
2017-04-16T23:45:53.638805+00:00 app[web.1]: ✖ 1 problem (0 errors, 1 warning)
2017-04-16T23:45:53.638806+00:00 app[web.1]: 
2017-04-16T23:45:53.638852+00:00 app[web.1]: 
2017-04-16T23:45:53.638893+00:00 app[web.1]: You may use special comments to disable some warnings.
2017-04-16T23:45:53.638959+00:00 app[web.1]: Use // eslint-disable-next-line to ignore the next line.
2017-04-16T23:45:53.639022+00:00 app[web.1]: Use /* eslint-disable */ to ignore all warnings in a file.
2017-04-16T23:45:53.864129+00:00 heroku[router]: at=info method=GET path="/Home" host=mums-the-word.herokuapp.com request_id=2c629c22-ab14-4dd1-9f36-8142070dbdb1 fwd="173.66.186.124" dyno=web.1 connect=0ms service=7667ms status=200 bytes=712 protocol=https
2017-04-16T23:45:54.523074+00:00 heroku[router]: at=info method=GET path="/static/js/bundle.js" host=mums-the-word.herokuapp.com request_id=029f1ee7-dd41-4cf7-a9cb-e15682b2aff2 fwd="173.66.186.124" dyno=web.1 connect=0ms service=509ms status=200 bytes=301708 protocol=https
2017-04-16T23:45:54.757095+00:00 heroku[router]: at=info method=GET path="/static/js/bundle.js.map" host=mums-the-word.herokuapp.com request_id=e8717995-11b5-4ca4-8cd6-564667cdd9ba fwd="173.66.186.124" dyno=web.1 connect=0ms service=106ms status=200 bytes=300717 protocol=https
2017-04-16T23:45:54.861240+00:00 heroku[router]: at=info method=GET path="/sockjs-node/info?t=1492386350582" host=mums-the-word.herokuapp.com request_id=22892f3b-adaa-41a1-bfa6-adfc4c237304 fwd="173.66.186.124" dyno=web.1 connect=0ms service=6ms status=200 bytes=363 protocol=https
2017-04-16T23:45:55.393578+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=mums-the-word.herokuapp.com request_id=274fc626-458b-4a09-b367-6c97dc3fbd93 fwd="173.66.186.124" dyno=web.1 connect=0ms service=3ms status=200 bytes=712 protocol=https
2017-04-16T23:46:06.476415+00:00 heroku[router]: at=info method=GET path="/sockjs-node/475/h3z14rb4/websocket" host=mums-the-word.herokuapp.com request_id=ca18c5f0-8738-4070-b206-2d618ce0aa18 fwd="173.66.186.124" dyno=web.1 connect=0ms service=11452ms status=101 bytes=484 protocol=https
2017-04-16T23:46:06.450668+00:00 heroku[router]: at=info method=GET path="/Home" host=mums-the-word.herokuapp.com request_id=b9da0009-20a8-4672-9022-6125878d7382 fwd="173.66.186.124" dyno=web.1 connect=1ms service=4ms status=200 bytes=712 protocol=https
2017-04-16T23:46:06.562871+00:00 heroku[router]: at=info method=GET path="/static/js/bundle.js" host=mums-the-word.herokuapp.com request_id=ac2c9d76-1326-4632-a560-54469eb885ce fwd="173.66.186.124" dyno=web.1 connect=0ms service=82ms status=200 bytes=301708 protocol=https
2017-04-16T23:46:06.955071+00:00 heroku[router]: at=info method=GET path="/static/js/bundle.js.map" host=mums-the-word.herokuapp.com request_id=c686d0fe-3c44-4573-a151-081aa01a5369 fwd="173.66.186.124" dyno=web.1 connect=0ms service=95ms status=200 bytes=300717 protocol=https
2017-04-16T23:46:07.165445+00:00 heroku[router]: at=info method=GET path="/sockjs-node/info?t=1492386362779" host=mums-the-word.herokuapp.com request_id=e9354b05-84a4-4108-b63d-bd9e9a3c252a fwd="173.66.186.124" dyno=web.1 connect=0ms service=5ms status=200 bytes=363 protocol=https
2017-04-16T23:46:07.591206+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=mums-the-word.herokuapp.com request_id=8c47d3a8-512b-449a-9c70-3d25fc9aeaf7 fwd="173.66.186.124" dyno=web.1 connect=0ms service=5ms status=200 bytes=712 protocol=https
2017-04-16T23:56:14.440873+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=932e8792-017c-4a4c-bd4b-635596816c02 fwd="173.66.186.124" dyno=web.1 connect=0ms service=6ms status=404 bytes=415 protocol=http
2017-04-16T23:56:14.422222+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=1d10a3b6-ffe7-4646-b2d4-20f31f8e0c9e fwd="173.66.186.124" dyno=web.1 connect=1ms service=9ms status=404 bytes=415 protocol=http
2017-04-16T23:59:06.600052+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=b8cc88d2-857e-421c-b0ba-4a78034b8f61 fwd="173.66.186.124" dyno=web.1 connect=1ms service=3ms status=404 bytes=415 protocol=http
2017-04-16T23:59:06.578851+00:00 heroku[router]: at=info method=GET path="/api/spots" host=mums-the-word.herokuapp.com request_id=a4f3c10e-cb64-4900-bec2-ce38ffad40b6 fwd="173.66.186.124" dyno=web.1 connect=1ms service=6ms status=404 bytes=415 protocol=http
2017-04-16T23:59:18.251796+00:00 heroku[router]: at=info method=GET path="/Home" host=mums-the-word.herokuapp.com request_id=217b6cac-5c0b-473a-80fb-8fdab80371a6 fwd="173.66.186.124" dyno=web.1 connect=1ms service=4ms status=200 bytes=712 protocol=https
2017-04-16T23:59:18.281299+00:00 heroku[router]: at=info method=GET path="/sockjs-node/025/1jghlo2d/websocket" host=mums-the-word.herokuapp.com request_id=ed6ffb46-49a9-487b-837e-1f9e7ce84b9c fwd="173.66.186.124" dyno=web.1 connect=0ms service=790932ms status=101 bytes=129 protocol=https
2017-04-16T23:59:18.446294+00:00 heroku[router]: at=info method=GET path="/static/js/bundle.js" host=mums-the-word.herokuapp.com request_id=d816344d-f50b-4bb5-b59b-27969880eaac fwd="173.66.186.124" dyno=web.1 connect=0ms service=127ms status=200 bytes=301708 protocol=https
2017-04-16T23:59:18.984086+00:00 heroku[router]: at=info method=GET path="/sockjs-node/info?t=1492387154699" host=mums-the-word.herokuapp.com request_id=1e742e2f-4019-44aa-8895-e59971af755b fwd="173.66.186.124" dyno=web.1 connect=0ms service=3ms status=200 bytes=361 protocol=https
2017-04-16T23:59:18.961442+00:00 heroku[router]: at=info method=GET path="/static/js/bundle.js.map" host=mums-the-word.herokuapp.com request_id=d89518ff-166b-4663-a714-983f9e70ec78 fwd="173.66.186.124" dyno=web.1 connect=0ms service=152ms status=200 bytes=300717 protocol=https
2017-04-16T23:59:19.302117+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=mums-the-word.herokuapp.com request_id=e362bd23-461c-482b-843f-ebf527bfbc5f fwd="173.66.186.124" dyno=web.1 connect=1ms service=13ms status=200 bytes=712 protocol=https

```

I also attempted to change it to the https and but am still getting the access link. I am thinking that you are correct something isn't connecting to the database.

<img width="667" alt="screenshot 2017-04-16 20 06 04" src="https://cloud.githubusercontent.com/assets/24941303/25075317/28a15540-22e0-11e7-85fa-05b370e42ebb.png">

**Comment by evalaidc** [comment]
I also used this site to try to connect mlab to my app. except I didnt' really understand the last step.

https://medium.com/@s1akr/deploying-a-mern-mongo-express-react-node-stack-web-app-on-to-heroku-d6a7745f88ba

**Comment by evalaidc** [comment]
or I just checked mlab. and saw this. could this possibly be affecting it because it is trying to go into a production env?

<img width="1173" alt="screenshot 2017-04-16 20 21 56" src="https://cloud.githubusercontent.com/assets/24941303/25075431/76eade36-22e2-11e7-9850-d038388c197f.png">

**Comment by superbuggy** [comment]
hrm..
This line in your heroku logs makes me think the connection was successful:
```
2017-04-16T23:42:57.436765+00:00 app[api.1]: MongoDB connected
```

Can you change the urls in your seed data to `https://` also?

I'm thinking it's just blocking these images...

**Comment by superbuggy** [comment]
> Can you change the urls in your seed data to https:// also?
>
> I'm thinking it's just blocking these images...


On second thought, that doesn't seem to be it. I'd still convert everything from `http` to `https`. What does your express file look like?

**Comment by evalaidc** [comment]
this is my server.js file
```js
const express = require('express')
const parser = require('body-parser');
const mongoose = require('../db/connection.js');
const Spot = require('../db/models.js').Spot

const app = express()
const router = express.Router()
// maybe use this to connect front end to backend, cross origin resource sharing
app.use(function(req, res, next) {
 res.setHeader('Access-Control-Allow-Origin', '*');
 res.setHeader('Access-Control-Allow-Credentials', 'true');
 res.setHeader('Access-Control-Allow-Methods', 'GET,HEAD,OPTIONS,POST,PUT,DELETE');
 res.setHeader('Access-Control-Allow-Headers', 'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers')

 //and remove caching so we get the most recent updates
  res.setHeader('Cache-Control', 'no-cache')
  next()
 })




app.set('view engine', 'react')

app.set("port", process.env.PORT || 3001)
app.use("/assets", express.static("public"))
app.use(parser.urlencoded({extended: true}))
app.use(parser.json())

//Use our router configuration when we call /api
app.use('/api', router)

//now we can set the route path & initialize the API
router.get('/', function(req, res) {
 res.json({ message: 'API Initialized!'});
})
// show all spots
router.get('/spots', function(req, res){
  Spot.find({}).then( function(spots){
    res.json(spots)
  })
})

// create a new spot
router.post("/spots/new", function(req, res){
  var spot = new Spot({
    title: req.body.title,
    author: req.body.author,
    blurb: req.body.blurb,
    photo_url: req.body.photo_url,
    address: req.body.address,
    longitude: req.body.longitude,
    latitude: req.body.latitude
  })

  spot.save(function(err, spot) {
   if (err){
    console.log(err);
  }
   })
});


// show 1 specific spot
router.get("/spots/:title", function(req,res) {
  Spot.findOne({title: req.params.title}).then(function(spot){
    res.json(spot)
  })
})


// delete a certain spot
router.delete("/spots/:title", function(req, res){
  Spot.findOneAndRemove({title: req.params.title}).then(function(){
    res.json({success: true});
  });
});

// listen for the server request
app.listen(app.get("port"), () => {
  console.log(`api running`);
})
```

**Comment by superbuggy** [comment]
ah! remove `/api/` from your axios path in your react views. I jumped the gun and assumed you had followed that convention.

**Comment by evalaidc** [comment]
I did follow that convention, but I just used router functionality to change all of then so i could just use router instead.

```
//Use our router configuration when we call /api
app.use('/api', router)
```

**Comment by evalaidc** [comment]
I think that was the same convention that the MERN tutorial angel sent out said to use. and it worked on my local host that way

**Comment by superbuggy** [comment]
Ah! I missed that at first pass, my apologies. Would you mind pushing your code and linking your repo? I'm traveling back tomorrow and may not get a chance before Tuesday, just to let you know.

**Comment by evalaidc** [comment]
No, Thanks for looking at it. I have been stumped for a couple of days now. 
It is possible to have a mern app deployed to heroku. or should I have uploaded it similar to the project 3. where you upload the backend separate from the front?

https://github.com/evalaidc/mums_the_word

**Comment by superbuggy** [comment]
It should be! Let me see if I can't shed any light on this.
