### ISSUE TITLE
Deploying MEAN

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/project4#483]
I'm getting this error 
```
2017-04-07T15:43:44.418610+00:00 app[web.1]: events.js:160
2017-04-07T15:43:44.418611+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-04-07T15:43:44.418612+00:00 app[web.1]:       ^
2017-04-07T15:43:44.420173+00:00 app[web.1]: MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
2017-04-07T15:43:44.420175+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:327:35)
2017-04-07T15:43:44.420176+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-07T15:43:44.420177+00:00 app[web.1]:     at Pool.emit (events.js:188:7)
2017-04-07T15:43:44.420178+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:274:12)
2017-04-07T15:43:44.420178+00:00 app[web.1]:     at Connection.g (events.js:291:16)
2017-04-07T15:43:44.420179+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-04-07T15:43:44.420180+00:00 app[web.1]:     at Connection.emit (events.js:191:7)
2017-04-07T15:43:44.420180+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:177:49)
2017-04-07T15:43:44.420181+00:00 app[web.1]:     at Socket.g (events.js:291:16)
2017-04-07T15:43:44.420182+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-07T15:43:44.420183+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2017-04-07T15:43:44.420183+00:00 app[web.1]:     at connectErrorNT (net.js:1025:8)
2017-04-07T15:43:44.420185+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-07T15:43:44.420185+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-07T15:43:44.632379+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-07T15:43:44.633524+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-07T15:43:44.616588+00:00 heroku[web.1]: Process exited with status 1
2017-04-07T15:43:47.328032+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-04-07T15:43:50.452370+00:00 app[web.1]: Connected
2017-04-07T15:43:50.464703+00:00 app[web.1]: 
2017-04-07T15:43:50.464707+00:00 app[web.1]: events.js:160
2017-04-07T15:43:50.464708+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-04-07T15:43:50.464708+00:00 app[web.1]:       ^
2017-04-07T15:43:50.465971+00:00 app[web.1]: MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
2017-04-07T15:43:50.465973+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:327:35)
2017-04-07T15:43:50.465974+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-07T15:43:50.465974+00:00 app[web.1]:     at Pool.emit (events.js:188:7)
2017-04-07T15:43:50.465975+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:274:12)
2017-04-07T15:43:50.465976+00:00 app[web.1]:     at Connection.g (events.js:291:16)
2017-04-07T15:43:50.465976+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-04-07T15:43:50.465977+00:00 app[web.1]:     at Connection.emit (events.js:191:7)
2017-04-07T15:43:50.465978+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:177:49)
2017-04-07T15:43:50.465978+00:00 app[web.1]:     at Socket.g (events.js:291:16)
2017-04-07T15:43:50.465979+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-07T15:43:50.465979+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2017-04-07T15:43:50.465980+00:00 app[web.1]:     at connectErrorNT (net.js:1025:8)
2017-04-07T15:43:50.465981+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-07T15:43:50.465981+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-07T15:43:50.616689+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-07T15:43:50.596713+00:00 heroku[web.1]: Process exited with status 1
2017-04-07T15:43:55.092637+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cryptic-shelf-99175.herokuapp.com request_id=17062d6d-207b-4c1e-ad28-4d5f4bec5e9c fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-07T15:43:55.330758+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cryptic-shelf-99175.herokuapp.com request_id=97db9ce1-797d-4262-92ce-192298c8b66f fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-07T15:44:24.689850+00:00 app[api]: Detach MONGOLAB_SILVER (@ref:mongolab-horizontal-13480) by user nyketha.lyken@gmail.com
2017-04-07T15:44:24.689850+00:00 app[api]: Release v13 created by user nyketha.lyken@gmail.com
2017-04-07T15:44:25.012917+00:00 app[api]: Release v13 created by user nyketha.lyken@gmail.com
2017-04-07T15:44:25.432993+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-07T15:44:27.795318+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-04-07T15:44:30.862799+00:00 app[web.1]: Connected
2017-04-07T15:44:30.872339+00:00 app[web.1]: 
2017-04-07T15:44:30.872343+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-04-07T15:44:30.872342+00:00 app[web.1]: events.js:160
2017-04-07T15:44:30.872344+00:00 app[web.1]:       ^
2017-04-07T15:44:30.873282+00:00 app[web.1]: MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
2017-04-07T15:44:30.873294+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:327:35)
2017-04-07T15:44:30.873295+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-07T15:44:30.873296+00:00 app[web.1]:     at Pool.emit (events.js:188:7)
2017-04-07T15:44:30.873296+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:274:12)
2017-04-07T15:44:30.873297+00:00 app[web.1]:     at Connection.g (events.js:291:16)
2017-04-07T15:44:30.873297+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-04-07T15:44:30.873298+00:00 app[web.1]:     at Connection.emit (events.js:191:7)
2017-04-07T15:44:30.873299+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:177:49)
2017-04-07T15:44:30.873299+00:00 app[web.1]:     at Socket.g (events.js:291:16)
2017-04-07T15:44:30.873300+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-07T15:44:30.873300+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2017-04-07T15:44:30.873301+00:00 app[web.1]:     at connectErrorNT (net.js:1025:8)
2017-04-07T15:44:30.873308+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-07T15:44:30.873309+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-07T15:44:30.991440+00:00 heroku[web.1]: Process exited with status 1
2017-04-07T15:44:31.019511+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-07T15:44:45.531734+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cryptic-shelf-99175.herokuapp.com request_id=b242b9a6-4702-4483-8056-c06e8b837040 fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-07T15:44:45.803777+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cryptic-shelf-99175.herokuapp.com request_id=985e8afd-19cc-4c78-8589-ca8536fa6988 fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-07T15:45:29.785678+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cryptic-shelf-99175.herokuapp.com request_id=c51d55b3-e767-46ee-ba1f-19109e86f479 fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
2017-04-07T15:45:30.095546+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cryptic-shelf-99175.herokuapp.com request_id=5555362a-61af-4862-89e5-95c2de916415 fwd="50.200.196.50" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by amaseda** [comment]
You probably need to use Heroku's mongoLab add-on in order to connect to your deployed database. Check this out and let me know if you have any questions. https://devcenter.heroku.com/articles/mongolab

**Comment by Nykke** [comment]
James helped me fix it. thanks!
