### ISSUE TITLE
SHOPDROP

### ISSUE THREAD

**Issue by lgmusic24** [ga-wdi-exercises/project4#492]
Still having trouble with config file :(

node server.js
module.js:487
    throw err;
    ^

Error: Cannot find module './configure/db'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/lgmusic24/project4/server.js:9:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by AndyWhitley** [comment]
Hi Luisa, could you please push your current code up to Github and send me link to your GitHub repo so I can look through your app?

**Comment by lgmusic24** [comment]
link
https://github.com/lgmusic24/SHOPDROP.git
