### ISSUE TITLE
running omniauth twitter in production enviornment

### ISSUE THREAD

**Issue by pdavies88** [ga-wdi-exercises/project4#52]
i was able to use jesses tutorial to set up omni auth twitter login to work locally using the 127.0.0.1.3000 callback url. I thought I would just need switch the callback url to my application address /auth/twitter/callback but i'm getting an error in the deployed heroku version and can't seem to find the fix any suggestions?

thanks

**Comment by pdavies88** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://freebie-findr.herokuapp.com/auth/twitter Failed to load resource: the server

**Comment by RobertAKARobin** [comment]
Try `heroku logs --tail`. This will display the logs for your app and update them automatically.

If you don't see the answer in there, try `heroku run rails c`. This opens the Rails console on the Heroku server. Often times, this tells you exactly what the problem was.

Failing both of those, let us know!

**Comment by jshawl** [comment]
did you configure your twitter application to have the new callback uri? i.e. freebie-finder.heroku... instead 127.0.0.1 at apps.twitter.com?

**Comment by pdavies88** [comment]
yeah i changed it to https://freebie-findr.herokuapp.com/auth/twitter/callback

**Comment by pdavies88** [comment]
```
2015-09-18T13:13:36.759364+00:00 app[web.1]: I, [2015-09-18T13:13:36.759257 #3]  INFO -- omniauth: (twitter) Request phase initiated.
2015-09-18T13:13:37.019575+00:00 heroku[router]: at=info method=GET path="/auth/twitter" host=freebie-findr.herokuapp.com request_id=f5497035-7367-446f-9a4e-a5a07d1a6141 fwd="69.143.134.53" dyno=web.1 connect=1ms service=277ms status=500 bytes=1754
2015-09-18T13:13:37.014127+00:00 app[web.1]: 
2015-09-18T13:13:37.014131+00:00 app[web.1]: OAuth::Unauthorized (400 Bad Request):
2015-09-18T13:13:37.014134+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:136:in `get_request_token'
2015-09-18T13:13:37.014132+00:00 app[web.1]:   vendor/bundle/ruby/2.0.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:216:in `token_request'
```
