### ISSUE TITLE
issue running seeds.js file

### ISSUE THREAD

**Issue by jordanbrauner** [ga-wdi-exercises/project4#72]
I tried running my seeds.js file and expected the database "project4test" to be created and populated with card_data.json. Instead I got a syntax error. I looked for the unexpected "}" but couldn't find it. The error message is pasted below.

My repo link is https://github.com/jordanbrauner/Project-4

```
in ~/wdi/projects/project-4 on master*
$ node db/seeds.js
module.js:463
    throw err;
    ^

SyntaxError: /Users/Jordan/wdi/projects/project-4/db/card_data.json: Unexpected token }
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:460:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Jordan/wdi/projects/project-4/db/seeds.js:2:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by RobertAKARobin** [comment]
Try using this:

http://jsonlint.com/

It's saved my life approximately 5000 times.

**Comment by amaseda** [comment]
What happens if you remove the extra commas on lines 15, 26 and 27 in `card_data.json`?

**Comment by jordanbrauner** [comment]
Ack! I have no idea how I missed those. Thanks a lot!
