### ISSUE TITLE
Seeding Issue

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#83]
I am running through the lesson plan (https://github.com/ga-dc/curriculum/tree/master/10-angular/resources-and-factories) to make sure I am not so rusty in Angular and I am getting an error in running `rake db:seed` after i dropped, created, and migrated. Postgresql is running.  I am getting: 

```
NoMethodError: undefined method `[]' for nil:NilClass
/Users/danielalexander/wdi/sandbox/grumblr_rails_api/db/seeds.rb:40:in `comment'
/Users/danielalexander/wdi/sandbox/grumblr_rails_api/db/seeds.rb:51:in `block (2 levels) in <top (required)>'
/Users/danielalexander/wdi/sandbox/grumblr_rails_api/db/seeds.rb:50:in `times'
/Users/danielalexander/wdi/sandbox/grumblr_rails_api/db/seeds.rb:50:in `block in <top (required)>'
/Users/danielalexander/wdi/sandbox/grumblr_rails_api/db/seeds.rb:43:in `each'
/Users/danielalexander/wdi/sandbox/grumblr_rails_api/db/seeds.rb:43:in `<top (required)>'
/Users/danielalexander/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/danielalexander/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/danielalexander/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/danielalexander/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/danielalexander/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/Users/danielalexander/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/Users/danielalexander/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
```

This isn't even my seed data or backend, I just want to be up to speed by practicing this again before I start on mine.

**Comment by RobertAKARobin** [comment]
Have you pulled from Github recently?

Make sure your seeds file looks like this one:

https://github.com/ga-dc/grumblr_rails_api/blob/master/db/seeds.rb

**Comment by dan-ator** [comment]
It is actually the backend api that we had used in class, which for me was working back then. (I remember there was something we had to add to it to make it work, which is why I didn't just clone from scratch)

**Comment by RobertAKARobin** [comment]
I just cloned it down, and it works perfectly fine. I'd try re-cloning.

**Comment by dan-ator** [comment]
Thanks.
