### ISSUE TITLE
Cannot display public folder content

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project4#84]
I have just set up my express backend and setup my api which works fine but now I am trying to serve my public views but I am running into this error.

```
Error: No default engine was specified and no extension was provided.
   at new View (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/express/lib/view.js:62:11)
   at EventEmitter.render (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/express/lib/application.js:569:12)
   at ServerResponse.render (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/express/lib/response.js:961:7)
   at /Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/server/app.js:24:7
   at Layer.handle [as handle_request] (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/express/lib/router/index.js:312:13)
   at /Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/express/lib/router/index.js:271:10)
   at SendStream.error (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/serve-static/index.js:120:7)
   at emitOne (events.js:77:13)
   at SendStream.emit (events.js:169:7)
   at SendStream.error (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/send/index.js:245:17)
   at SendStream.onStatError (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/send/index.js:356:12)
   at next (/Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/send/index.js:658:28)
   at /Users/andreshonubi/wdi/projects/Project-4-Pop-Collector/node_modules/send/index.js:666:23
```

In my `app.js` file I have `app.use(express.static(__dirname + '../public'));`

**Comment by RobertAKARobin** [comment]
You need `app.set('view engine', 'hbs');`
